"use client";
import {useMemo,useState} from "react";
import {exams} from "@/lib/exams";

type Level="10th"|"12th"|"Graduate"|"Postgraduate"|"Professional";
const levelRank:Record<Level,number>={"10th":1,"12th":2,"Graduate":3,"Postgraduate":4,"Professional":4};
function requiredLevel(q:string):Level{
 const s=q.toLowerCase();
 if(s.includes("mbbs")||s.includes("master")||s.includes("postgraduate")) return "Postgraduate";
 if(s.includes("graduate")||s.includes("degree")||s.includes("b.ed")||s.includes("d.el.ed")) return "Graduate";
 if(s.includes("12th")||s.includes("10+2")) return "12th";
 return "10th";
}
const categories=["All",...Array.from(new Set(exams.map(e=>e.category)))];
const official=[["UPSC","https://www.upsc.gov.in/"],["SSC","https://ssc.gov.in/"],["IBPS","https://www.ibps.in/"],["Railways","https://indianrailways.gov.in/"],["NTA","https://www.nta.ac.in/"],["RBI","https://www.rbi.org.in/"],["SBI Careers","https://sbi.co.in/web/careers"],["CTET","https://ctet.nic.in/"],["JPSC","https://jpsc.gov.in/"],["Army","https://joinindianarmy.nic.in/"],["Navy","https://www.joinindiannavy.gov.in/"],["AFCAT","https://afcat.edcil.co.in/"]];

export default function Home(){
 const[q,setQ]=useState(""),[cat,setCat]=useState("All"),[age,setAge]=useState(""),[edu,setEdu]=useState<Level>("Graduate"),[result,setResult]=useState<any[]|null>(null),[showAll,setShowAll]=useState(false);
 const[saved,setSaved]=useState<string[]>(()=>typeof window==="undefined"?[]:JSON.parse(localStorage.getItem("sarkariprep_saved")||"[]"));
 const list=useMemo(()=>exams.filter(e=>(cat==="All"||e.category===cat)&&(!q||[e.name,e.organization,e.category,e.qualifications].join(" ").toLowerCase().includes(q.toLowerCase()))),[q,cat]);
 const visible=showAll?list:list.slice(0,9);
 function save(slug:string){const n=saved.includes(slug)?saved.filter(x=>x!==slug):[...saved,slug];setSaved(n);localStorage.setItem("sarkariprep_saved",JSON.stringify(n))}
 function check(){const n=Number(age);const r=levelRank[edu];setResult(exams.filter(e=>n>=e.minAge&&n<=e.maxAge&&levelRank[requiredLevel(e.qualifications)]<=r))}
 return <div>
 <div className="top"/>
 <header className="nav"><div className="wrap navInner"><a className="brand" href="/">Sarkari<span>Prep</span></a><nav className="navlinks"><a href="#exams">Exams</a><a href="#eligibility">Eligibility</a><a href="#jobs">Jobs</a><a href="#resources">Preparation</a><a href="#official">Official</a></nav><a className="savedNav" href="#saved">★ {saved.length}</a></div></header>

 <section className="hero"><div className="wrap heroInner"><div className="heroCopy"><span className="tag orange">🇮🇳 STUDENT-FIRST EXAM PLATFORM</span><h1>Government exams ko <span>simple & structured</span> banao.</h1><p>Exam choose karne se lekar eligibility, syllabus, application, admit card aur result tak — student ko jo chahiye, ek organised dashboard mein.</p><div className="heroSearch"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search exam, job, organisation…"/><button onClick={()=>document.getElementById("exams")?.scrollIntoView({behavior:"smooth"})}>Search</button></div><div className="trustRow"><span>✓ Official-source links</span><span>✓ 10th to PG</span><span>✓ Mobile friendly</span></div></div><div className="heroPanel"><div className="panelLabel">QUICK FIND</div><h3>Apna route choose karo</h3><div className="route"><b>🎓 Qualification</b><span>10th • 12th • Graduate • PG</span></div><div className="route"><b>🧑‍💼 Job type</b><span>SSC • Banking • Railway • Defence</span></div><div className="route"><b>📚 Preparation</b><span>Syllabus • PYQ • Mock • Revision</span></div><a href="#eligibility" className="routeBtn">Check my eligibility →</a></div></div></section>

 <section className="section"><div className="wrap"><div className="sectionHead"><div><span className="eyebrow">START HERE</span><h2>Student journey — 6 clear steps</h2></div><p>No confusion. Pehle exam discover karo, phir requirements aur preparation follow karo.</p></div><div className="steps">{[["01","DISCOVER","Apne qualification aur interest ke hisaab se exam find karo."],["02","CHECK","Age, qualification, relaxation aur physical requirements dekho."],["03","PLAN","Syllabus + exam pattern + PYQ ko roadmap banao."],["04","APPLY","Documents ready karo aur official portal se form bharo."],["05","PREPARE","Mock tests, revision aur mistake analysis follow karo."],["06","TRACK","Admit card → answer key → result → next stage track karo."]].map(x=><div className="step" key={x[0]}><b>{x[0]}</b><span>{x[1]}</span><p>{x[2]}</p></div>)}</div></div></section>

 <section className="section light" id="exams"><div className="wrap"><div className="sectionHead"><div><span className="eyebrow">EXAM DIRECTORY</span><h2>Find your government exam</h2></div><p>{list.length} exams match your current search/filter.</p></div><div className="filterBar"><div className="filterScroll">{categories.map(c=><button className={cat===c?"filter active":"filter"} key={c} onClick={()=>{setCat(c);setShowAll(false)}}>{c}</button>)}</div></div><div className="examGrid">{visible.map(e=><article className="examCard" key={e.slug}><div className="examMeta"><span className="tag">{e.category}</span><button className="bookmark" onClick={()=>save(e.slug)} aria-label="Save exam">{saved.includes(e.slug)?"★":"☆"}</button></div><h3>{e.name}</h3><p className="org">{e.organization}</p><div className="miniFacts"><div><small>Qualification</small><b>{e.qualifications}</b></div><div><small>Age</small><b>{e.minAge===0?"No general limit":e.minAge+"–"+e.maxAge+" yrs"}</b></div><div><small>Vacancies</small><b>{e.vacancies}</b></div></div><div className="cardLinks"><a className="primaryLink" href={"/exams/"+e.slug}>View complete guide</a><a href={e.officialUrl} target="_blank" rel="noopener">Official ↗</a></div></article>)}</div>{!list.length&&<div className="empty">No exam found. Try another keyword or category.</div>}{list.length>9&&<button className="showMore" onClick={()=>setShowAll(!showAll)}>{showAll?"Show less ↑":"View all "+list.length+" exams →"}</button>}</div></section>

 <section className="section" id="eligibility"><div className="wrap"><div className="eligLayout"><div><span className="eyebrow">SMART TOOL</span><h2>“Mere liye kaunsa exam?”</h2><p>Age + education select karo. SarkariPrep indicative matches dikhayega. Final eligibility hamesha latest official notification se verify karein.</p><div className="eligForm"><label>Age<input type="number" min="15" max="70" value={age} onChange={e=>setAge(e.target.value)} placeholder="e.g. 24"/></label><label>Education<select value={edu} onChange={e=>setEdu(e.target.value as Level)}><option>10th</option><option>12th</option><option>Graduate</option><option>Postgraduate</option><option>Professional</option></select></label><button onClick={check}>Find matching exams</button></div></div><div className="resultPanel">{result===null?<><div className="resultIcon">✓</div><b>Smart eligibility</b><p>Age aur education enter karke apne likely exam options dekho.</p></>:<><div className="resultCount">{result.length}</div><b>Indicative matches</b><div className="resultList">{result.slice(0,7).map(e=><a href={"/exams/"+e.slug} key={e.slug}>{e.name}<span>→</span></a>)}</div>{result.length>7&&<a className="resultMore" href="#exams">See all in exam directory →</a>}</>}</div></div></div></section>

 <section className="section light" id="jobs"><div className="wrap"><div className="sectionHead"><div><span className="eyebrow">JOB DISCOVERY</span><h2>Qualification ke hisaab se jobs</h2></div></div><div className="jobGrid">{[["10th / ITI","🔧","Railway Group D, technical/trade & post-specific recruitments"],["12th Pass","🎓","SSC CHSL, selected Defence/Railway & other 10+2 exams"],["Graduate","🧑‍💼","UPSC, SSC CGL, Banking, Railway & State PSC"],["Defence / Police","🛡️","NDA, CDS, CAPF, AFCAT & state police pathways"],["Teaching","🏫","CTET, UGC NET & recruitment-body-specific teaching"],["Engineering / PSU","⚙️","GATE and technical/PSU recruitment pathways"]].map(x=><a className="jobCard" href="#exams" key={x[0]}><span>{x[1]}</span><div><b>{x[0]}</b><p>{x[2]}</p></div><strong>→</strong></a>)}</div></div></section>

 <section className="section" id="resources"><div className="wrap"><div className="sectionHead"><div><span className="eyebrow">PREPARATION</span><h2>Complete preparation system</h2></div></div><div className="resourceGrid">{[["01","Syllabus","Official syllabus ko topics aur priority mein break karo."],["02","PYQ","Previous papers se pattern, difficulty aur repeated topics samjho."],["03","Mock","Sectional → full mock → analysis → weak-topic revision."],["04","Revision","1-day, 7-day aur 21-day spaced revision cycles."],["05","Documents","Photo, signature, ID, certificates aur category documents checklist."],["06","Current Affairs","Official releases + trusted sources se concise notes."]].map(x=><article className="resourceCard" key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></div></section>

 <section className="section officialSection" id="official"><div className="wrap"><div className="sectionHead"><div><span className="eyebrow">SOURCE OF TRUTH</span><h2>Live information — official portal par</h2></div><p>Current notification, application, admit card, answer key aur result ke liye direct authority website.</p></div><div className="officialGrid">{official.map(x=><a href={x[1]} target="_blank" rel="noopener" className="officialCard" key={x[0]}><b>{x[0]}</b><span>Open official ↗</span></a>)}</div></div></section>

 <section className="section" id="saved"><div className="wrap"><div className="sectionHead"><div><span className="eyebrow">YOUR SHORTLIST</span><h2>Saved exams</h2></div></div>{saved.length?<div className="savedGrid">{saved.map(s=>{const e=exams.find(x=>x.slug===s);return e?<a className="savedCard" href={"/exams/"+e.slug} key={s}><b>{e.name}</b><span>{e.category} · {e.organization}</span></a>:null})}</div>:<div className="empty">Exam cards par ☆ tap karke apni shortlist banao.</div>}</div></section>

 <section className="section faq"><div className="wrap"><div className="sectionHead"><div><span className="eyebrow">HELPDESK</span><h2>Common questions</h2></div></div><div className="faqGrid"><details><summary>Latest vacancy ko final kaise verify karun?</summary><p>Recruiting authority ke latest official notification ko source of truth rakhein. Revised vacancy notice aa sakta hai.</p></details><details><summary>Admit card aur result kahan milega?</summary><p>Exam guide se official portal open karke current candidate/result section use karein.</p></details><details><summary>Age relaxation kahan check hogi?</summary><p>Har recruitment ki latest notification mein category/post-specific relaxation check karein.</p></details><details><summary>Kya SarkariPrep government website hai?</summary><p>Nahi. Ye independent student-information platform hai. Application details official authority se verify karein.</p></details></div></div></section>
 <footer className="footer"><div className="wrap footerInner"><div><div className="brand">Sarkari<span>Prep</span></div><p>Student-first government exam & job information platform.</p></div><div><b>Important</b><p>Not a government website. Always verify latest official notification.</p></div></div></footer>
 </div>
}