export type AutoExamOverride = {
 slug:string; name:string; organization:string; notificationUrl:string; sourceUrl:string; lastVerified:string; detectedAt:string; confidence:"medium"|"high"; evidenceCount:number; evidence:string[]; evidenceSnippets?:string[]; sourceTitle?:string;
 familySlug?:string; cycleSlug?:string; cycleYear?:number;
 applicationDates?:string; lastDate?:string; examDate?:string; vacancies?:string; minAge?:number; maxAge?:number; fee?:string; correctionDates?:string; qualification?:string; selectionProcess?:string; payScale?:string; nationality?:string; domicile?:string; ageRelaxation?:string; dataCertainty?:"confirmed"|"tentative"|"calendar"; applicationStatus?:"open"|"closed"|"upcoming"|"unknown"; stale?:boolean; refreshedThisCycle?:boolean;
};

export const autoExamDataMeta = {
  "generatedAt": "2026-10-06",
  "sourceCount": 78,
  "overrideCount": 11,
  "policy": "Only conservative values extracted from an official notice/bulletin are applied. Missing or ambiguous fields are never invented."
};

export const autoExamData:Record<string,AutoExamOverride> = {
  "upsc-capf-2026": {
    "vacancies": "1108073 notified",
    "qualification": "Diploma in Company Law/Labour Laws/Public Administration",
    "slug": "upsc-capf-2026",
    "cycleSlug": "upsc-capf-2026",
    "name": "UPSC CAPF Assistant Commandants",
    "organization": "UPSC",
    "notificationUrl": "https://www.upsc.gov.in/sites/default/files/RT-FScrtyNotice-74-APFC-EPFO-Engl-210926.pdf",
    "sourceUrl": "https://www.upsc.gov.in/whats-new",
    "lastVerified": "2026-10-05",
    "detectedAt": "2026-10-05",
    "confidence": "high",
    "evidenceCount": 2,
    "evidence": [
      "vacancies",
      "qualification"
    ],
    "evidenceSnippets": [
      "non submission of affidavit for self name/father’s name discrepancy: 1110193, 6604928 Roll Number of On account of non suitability for the post: candidate 1108073 whose candidature On account of non submission of requisite certificate: has been 4102859 cancelled *Candidature of the candidate has been considered on OBC standards due to non submission of requisite disability certificate. Sd/- Under Secretary (SPC-II)",
      "Qualifications and Desirable DESIRABLE: Diploma in Company Law/Labour Laws/Public Administration"
    ],
    "sourceTitle": "Notice: 74 Posts of Assistant Provident Fund Commissioner, EPFO",
    "dataCertainty": "confirmed",
    "applicationStatus": "unknown",
    "refreshedThisCycle": false,
    "stale": true
  },
  "upsc-ese-2027": {
    "lastDate": "09.01.2027",
    "examDate": "09.01.2027",
    "slug": "upsc-ese-2027",
    "cycleSlug": "upsc-ese-2027",
    "name": "UPSC Engineering Services (Preliminary) Examination 2027",
    "organization": "UPSC",
    "notificationUrl": "https://www.upsc.gov.in/sites/default/files/Calendar-Year-2027-Engl-200526_0.pdf",
    "sourceUrl": "https://www.upsc.gov.in/whats-new",
    "lastVerified": "2026-10-05",
    "detectedAt": "2026-10-05",
    "confidence": "high",
    "evidenceCount": 2,
    "evidence": [
      "lastDate",
      "examDate"
    ],
    "evidenceSnippets": [
      "As on 20.05.2026 UNION PUBLIC SERVICE COMMISSION PROGRAMME OF EXAMINATIONS/RECRUITMENT TESTS (RTs) - 2027 Date of Last Date for Date of Duration Sl. No. Name of Examination Notification receipt of commencement of Exam Applications of Exam 09.01.2027 1. Reserved for UPSC RT/ Examination 2 Days (Saturday) 10.01.2027 2. Combined Geo-Scientist (Preliminary) Examination, 2027 02.09.2026 22.09.202",
      "Examination Notification receipt of commencement of Exam Applications of Exam 09.01.2027 "
    ],
    "sourceTitle": "Annual Calendar 2027",
    "dataCertainty": "confirmed",
    "applicationStatus": "unknown",
    "refreshedThisCycle": false,
    "stale": true
  },
  "ssc-stenographer-2026": {
    "lastDate": "06.10.2026",
    "applicationDates": "16.09.2026 to 06.10.2026",
    "examDate": "16.09.2026 to 06.10.2026",
    "qualification": "Number (URN), Common Application Form (CAF) and the fourth module i",
    "slug": "ssc-stenographer-2026",
    "cycleSlug": "ssc-stenographer-2026",
    "familySlug": "family-ssc-stenographer",
    "cycleYear": 2026,
    "name": "SSC Stenographer Grade C & D 2026",
    "organization": "SSC",
    "notificationUrl": "https://www.upsc.gov.in/sites/default/files/Notif-CmbSO-LDCE-2026-Engl-160926.pdf",
    "sourceUrl": "https://www.upsc.gov.in/whats-new",
    "lastVerified": "2026-10-05",
    "detectedAt": "2026-10-05",
    "confidence": "high",
    "evidenceCount": 4,
    "evidence": [
      "lastDate",
      "applicationDates",
      "examDate",
      "qualification"
    ],
    "evidenceSnippets": [
      "OFFICERS’ (GRADE-‘B’) LIMITED DEPARTMENTAL COMPETITIVE EXAMINATION, 2026 EXAMINATION NOTICE Date of Notification of Examination 16.09.2026 Last date for filling up of Application 06.10.2026 Date of Examination 12.12.2026 & 13.12.2026 (The Commission's website - https://upsc.gov.in) IMPORTANT INFORMATION FOR THE CANDIDATES The Online Application Portal of Union Public Service Commission for registration and filling u",
      "SUBMISSION OF APPLICATION: The Online Application can be filled from 16.09.2026 to 06.10.2026",
      "EXAMINATION NOTICE Date of Notification of Examination 16.09.2026 Last date for filling up of Application 06.10.2026",
      "educational qualification, etc. as may be sought by the Commission along with the Universal Registration Number (URN), Common Application Form (CAF) and the fourth module i"
    ],
    "sourceTitle": "Exam Notification: Combined Section Officers (Grade-&#039;B&#039;) LDCE - 2026 and Combined Stenographers (Grade - &#039;B&#039; - Grade - &#039;I&#039;) LDCE - 2022, 2023 and 2024",
    "dataCertainty": "confirmed",
    "applicationStatus": "open",
    "refreshedThisCycle": false,
    "stale": true
  },
  "upsc-cse-2026": {
    "lastDate": "20.07.2026",
    "vacancies": "001, notified",
    "minAge": 5,
    "maxAge": 5,
    "fee": "₹250",
    "qualification": "तकनीिशयन-बी / TECHNICIAN-B (अना",
    "selectionProcess": "िनधा रत यो ता ूनतम आव कता है तथा इसके होने पर अ थ िल खत परी ा/ सी",
    "payScale": "as in Pay on Matrix 20",
    "ageRelaxation": "rved for the respective category)",
    "slug": "upsc-cse-2026",
    "cycleSlug": "upsc-cse-2026",
    "name": "UPSC Civil Services Examination 2026",
    "organization": "UPSC",
    "notificationUrl": "https://www.isro.gov.in/media_isro/pdf/recruitmentNotice/2026/June/ISTRAC_BILINGUAL_ADVERTISEMENT_02_2026_26062026.pdf",
    "sourceUrl": "https://www.isro.gov.in/Careers.html",
    "lastVerified": "2026-10-05",
    "detectedAt": "2026-10-05",
    "confidence": "high",
    "evidenceCount": 8,
    "evidence": [
      "lastDate",
      "vacancies",
      "age",
      "fee",
      "qualification",
      "selectionProcess",
      "payScale",
      "ageRelaxation"
    ],
    "evidenceSnippets": [
      ". आयु की गणना, अहता ा , अनु भव इ ािद जैसे सभी योजनों के िलए 20.07.2026 (ऑनलाइन आवेदनों की ा हेतु अंितम तारीख) अंितम तारीख होगी। 20.07.2026 (LAST DATE FOR RECEIPT OF ON-LINE APPLICATIONS) will be the cut-off date for all purposes like computation of age, acquiring of qualification, experience etc. xxiv. अ थ यह सुिन त कर िक वे सभी संदभ म िव ापन के साथ-साथ आवेदन प म उपल अपे ाओं सिहत पा ता मानदं ड पूण करते ह एवं अनुदेशों का पालन करते ह। अत: अ िथयों से अनुरोध है िक िव ापन को ान से पढ़ और ऑनलाइन आवेदन प को भर तथा इस संबंध म िदए गए अनुदेशों के अनुसार उ को ुत कर। It is for the candidate to ensure that he / she fulfills the eligibility criteria and comply with the requirements and adheres to the instructions contained in this advertisement as well as in the application form in all respects. Candidates are therefore, urged to carefully read the advertisement and fill in the on-line application form and submit the same as per the instructions given in this regard. xxv. आवेदक की पूरी जानकारी, फोटो इ ािद के िबना आवेदन ुत करने पर, इसे तुरंत ही अ ीकृत िकया जाएगा। Applications submitted without complete information, photo of the applicant, etc. will summarily be rejected. xxvi. एक ही स म एक से अिधक पदों के िलए परी ा का समय एक होने की थित म , अ थ को सलाह दी जाती है िक वे परी ा दे ने के िलए एक ही पद का चयन कर। If a clash with the timing of the examination for multiple posts in the same session is observed, candidate is advised to choose one post for appearing in the examination. xxvii. िहंदी पांतर की ा ा के संदभ म िकसी भी कार की अ ता/िववाद की थित म, अं े ज़ी पांतर म उ खत िवषय –व ु को अंितम माना जाएगा। In case of any ambiguity / dispute arises on account of interpretation of Hindi version, contents enumerated in English version shall finally prevail. कृपया भत से संबंिधत नवीनतम अ तन थित हेतु हमारी वेबसाइट www.isro.gov.in / www.istrac.gov.in दे ख PLEASE VISIT OUR WEBSITES AT www.isro.gov.in / www.istrac.gov.in FOR LATEST UPDATES ON RECRUITMENT अ िथयों को सलाह दी जाती है िक वे केवल इसरो / इ ै क के सरकारी वेबसाइट ही दे ख एवं अनैितक त /दलालों ारा नकली वेबसाइट एवं सोिशयल मीिडया म डाले गए िवषयों से सावधान रह Candidates are advised to visit only the official websites of ISRO / ISTRAC and beware of FAKE websites and social media content put up by unscrupulous elements/ touts. ऑनलाइन आवेदन ा करने की अंितम तारीख 20.07.2026 है। LAST DATE FOR RECEIPT OF ON-LINE APPLICATIONS IS 20.07.2026 इसरो म सेवा आरं भ कर एवं जीवन वृि को सँवार, ितभाशाली वै ािनक एवं तकनीकी समु",
      "ade from NCVT नोट-पद कोड सं 001 के िलए, कुल 08 पदों म से, 05 पद इ ै क तथा 03 पद मु िनयं ण सुिवधा, हासन म भरने हे तु अिधसूिचत है । Note: For Post Code No. 001, out of the total 08 posts, 05 posts are notified for filling up at ISTRAC and 03 posts are notified for filling up at Master Control Facility (MCF), Hassan. तकनीकी सहायक / TECHNICAL ASSISTANT (अनु ज.जा. / ST- 01 – उ.पू .सै क, उिमयम म तै नाती के िलए िच त identif",
      "age limit by 05 years",
      "Application Fee of ₹250",
      "qualification & Mode of Field Vacancy Reserved for Standards Code. Experience Selection (ies) तकनीिशयन-बी / TECHNICIAN-B (अना",
      "Selection Process: िनधा रत यो ता ूनतम आव कता है तथा इसके होने पर अ थ िल खत परी ा/ सी",
      "Pay Level लगभग कुल प रल याँ Name of the post Post Code Approx. Gross Emoluments Age limit as in Pay on Matrix 20",
      "relaxation in upper age limit by 05 years for SC/ST candidates and 03 years for OBC candidates (wherever the posts are reserved for the respective category)"
    ],
    "sourceTitle": "Advt. No. ISTRAC:02:2026 dated 27.06.2026 - The Computer Based Test (CBT) is scheduled on 25.09.2026.",
    "dataCertainty": "tentative",
    "applicationStatus": "closed",
    "refreshedThisCycle": false,
    "stale": true
  },
  "lic-aao-2025": {
    "applicationDates": "5.0.34 to 5.0.44",
    "examDate": "12.03.2026",
    "correctionDates": "editor-alloyeditor-web@5.0.28/index';var MODULE_PATH='/o/frontend-editor-alloyeditor-web';AUI().applyConfig({groups:{alloyeditor:{base:MODULE_PATH+\"/js/\",combine:Liferay.AUI.getCombine(),filter:Liferay.AUI.getFilterConfi",
    "slug": "lic-aao-2025",
    "cycleSlug": "lic-aao-2025",
    "familySlug": "family-lic-aao",
    "cycleYear": 2025,
    "name": "LIC Assistant Administrative Officer 2025",
    "organization": "LIC",
    "notificationUrl": "https://licindia.in/recruitment-of-aao-generalists/-specialists/-assistant-engineers-2025",
    "sourceUrl": "https://licindia.in/careers",
    "lastVerified": "2026-10-05",
    "detectedAt": "2026-10-05",
    "confidence": "high",
    "evidenceCount": 3,
    "evidence": [
      "applicationDates",
      "examDate",
      "correctionDates"
    ],
    "evidenceSnippets": [
      "window\",\"node-core\"]}},root:MODULE_PATH+\"/invite_members/js/\"}}}); } catch(error) {console.error(error);}try {var MODULE_MAIN='contacts-web@5.0.34/index';var MODULE_PATH='/o/contacts-web';AUI().applyConfig({groups:{contactscenter:{base:MODULE_PATH+\"/js/\",combine:Liferay.AUI.getCombine(),filter:Liferay.AUI.getFilterConf",
      "EXAMINATION AE(ELECTRICAL) ​ FORMAT FOR MEDICAL REPORT FORMAT FOR STATEMENT OF HEALTH NOTICE-12.03.2026 \"REPRINTING APPLICATION FORM OF AAO (GENERALIST/SPECIALIST/ASSISTANT ENGINEERS)-",
      "editor-alloyeditor-web@5.0.28/index';var MODULE_PATH='/o/frontend-editor-alloyeditor-web';AUI().applyConfig({groups:{alloyeditor:{base:MODULE_PATH+\"/js/\",combine:Liferay.AUI.getCombine(),filter:Liferay.AUI.getFilterConfig(),modules:{\"liferay-alloy-editor\":{path:\"alloyeditor.js\",requires:[\"aui-component\",\"liferay-portle"
    ],
    "sourceTitle": "Recruitment of AAO Generalists Specialists Assistant Engineers 2025",
    "dataCertainty": "confirmed",
    "applicationStatus": "upcoming",
    "refreshedThisCycle": false,
    "stale": true
  },
  "ibps-clerk-2026": {
    "examDate": "13.08.2026",
    "correctionDates": "MODIFICATION OF THE EXAMINATION PROGRAMME PUBLISHED ON 13.08.2026 Reason for Modification: ൊപൊത വിദയൊഭയൊസ വകപിൊല പീ ൈപമറി ടീചർ ( ബധിര വിദയൊലയം) (എൻ. സി. എ. - ഈഴവ/ തിയ/ ബിലവ) (Cat. No. ",
    "qualification": "ertaking that all the topics mentioned under the sub head “Main Topics” may be covered in the question paper",
    "slug": "ibps-clerk-2026",
    "cycleSlug": "ibps-clerk-2026",
    "name": "IBPS Customer Service Associate XVI",
    "organization": "IBPS",
    "notificationUrl": "http://www.keralapsc.gov.in/sites/default/files/2026-09/after_confirmation_october_modified.pdf",
    "sourceUrl": "https://www.keralapsc.gov.in/",
    "lastVerified": "2026-10-05",
    "detectedAt": "2026-10-05",
    "confidence": "high",
    "evidenceCount": 3,
    "evidence": [
      "examDate",
      "correctionDates",
      "qualification"
    ],
    "evidenceSnippets": [
      "EXAMINATION PROGRAMME PUBLISHED ON 13.08.2026 Reason for Modification: ൊപൊത വിദയൊഭയൊസ വകപിൊല പീ ൈപമറി ടീചർ ( ബധിര വിദയൊലയം) (എൻ. സി. എ. - ഈഴവ/ തിയ/ ബിലവ) (Cat. No. ",
      "MODIFICATION OF THE EXAMINATION PROGRAMME PUBLISHED ON 13.08.2026 Reason for Modification: ൊപൊത വിദയൊഭയൊസ വകപിൊല പീ ൈപമറി ടീചർ ( ബധിര വിദയൊലയം) (എൻ. സി. എ. - ഈഴവ/ തിയ/ ബിലവ) (Cat. No. ",
      "educational qualifications prescribed for the post may also appear in the question paper. There is no undertaking that all the topics mentioned under the sub head “Main Topics” may be covered in the question paper"
    ],
    "sourceTitle": "Exam Schedule",
    "dataCertainty": "confirmed",
    "applicationStatus": "unknown",
    "refreshedThisCycle": false,
    "stale": true
  },
  "inicet-2026": {
    "lastDate": "31.10.2025",
    "applicationDates": "10.10.2025 to 30.10.2025",
    "examDate": "10.10.2025 to 30.10.2025",
    "vacancies": "2026 notified",
    "correctionDates": "edit/ 31.10.2025 (Upto ",
    "qualification": "treated as correct/ final and NTA will not entertain, under any circumstances, any request for change in information provided by the candidates",
    "domicile": "applicable)",
    "slug": "inicet-2026",
    "cycleSlug": "inicet-2026",
    "familySlug": "family-inicet",
    "cycleYear": 2026,
    "name": "INI-CET 2026",
    "organization": "AIIMS",
    "notificationUrl": "https://cdnbbsr.s3waas.gov.in/s388a839f2f6f1427879fc33ee4acf4f66/uploads/2025/10/20251010937989896.pdf",
    "sourceUrl": "https://www.nta.ac.in/NoticeBoardArchive",
    "lastVerified": "2026-10-05",
    "detectedAt": "2026-10-05",
    "confidence": "high",
    "evidenceCount": 7,
    "evidence": [
      "lastDate",
      "applicationDates",
      "examDate",
      "vacancies",
      "correctionDates",
      "qualification",
      "domicile"
    ],
    "evidenceSnippets": [
      "AT A GLANCE FEE DETAILS AND IMPORTANT DATES Activity Dates Online Submission of Application 10.10.2025 to 30.10.2025 Forms (Upto 05:00 PM) Last Date of Successful Transaction of Fee through Credit/ 31.10.2025 (Upto 11:50 PM) Debit Card/Net-Banking Fee Payable by candidates in INR: Category Fee payable General/Wards of Defence ₹ 850/- personnel and ex-servicemen/ (Rs. Eight Hundred & Fifty Only) OBC (NCL)* as per cen",
      "Online Submission of Application 10.10.2025 to 30.10.2025",
      "exams.nta.nic.in/sainik-school- society/ Online Submission of Application Form 10.10.2025 to 30.10.2025",
      "ate must be in possession of the Admit Card to appear in the examination. (b) Candidate may please note that Admit Card will not be sent by post. (c) In no case, the duplicate Admit Card for AISSEE-2026 would be issued at the Examination Centres. (d) Candidate must not mutilate/disfigure the Admit Card or change any entry made therein. (e) Candidates are advised to preserve their Admit Card in good condition for futu",
      "edit/ 31.10.2025 (Upto ",
      "educational qualification details, date of birth, etc during online registration for AISSEE-2026 will be treated as correct/ final and NTA will not entertain, under any circumstances, any request for change in information provided by the candidates",
      "Domicile Certificate. (f) Caste/Community/ Category Certificate (if applicable)"
    ],
    "sourceTitle": "All India Sainik School Entrance Exam (AISSEE)",
    "dataCertainty": "tentative",
    "applicationStatus": "closed",
    "refreshedThisCycle": false,
    "stale": true
  },
  "lic-aao-2026": {
    "lastDate": "08 March 2026",
    "applicationDates": "08 February 2026 to 08 March 2026",
    "examDate": "03 May 2026",
    "vacancies": "2026 notified",
    "correctionDates": "Correction in Particulars 10 March 2026 to 12 March 2026",
    "qualification": "a for NRI/OCI/ Foreign Nationals 25 3 Qualification and Qualifying examination codes 26 Chapter 7: Counselling and Reservation for Admission to MBBS, BAMS, BUMS, BSMS, BHMS, BDS and B",
    "nationality": "ure for Online Payment of Fee and Helpline for Payment 93 Related Queries 9 IX Replica of Application Form 96 10 X Important Points to Note 109 S",
    "domicile": "e seats of DU/ I",
    "slug": "lic-aao-2026",
    "cycleSlug": "lic-aao-2026",
    "familySlug": "family-lic-aao",
    "cycleYear": 2026,
    "name": "LIC Assistant Administrative Officer 2026",
    "organization": "LIC",
    "notificationUrl": "https://cdnbbsr.s3waas.gov.in/s37bc1ec1d9c3426357e69acd5bf320061/uploads/2026/02/202602231394640855.pdf",
    "sourceUrl": "https://www.nta.ac.in/NoticeBoardArchive",
    "lastVerified": "2026-10-05",
    "detectedAt": "2026-10-05",
    "confidence": "high",
    "evidenceCount": 8,
    "evidence": [
      "lastDate",
      "applicationDates",
      "examDate",
      "vacancies",
      "correctionDates",
      "qualification",
      "nationality",
      "domicile"
    ],
    "evidenceSnippets": [
      "NT INFORMATION AND DATES AT A GLANCE EVENTS DATES Online Submission of Application Form 08 February 2026 to 08 March 2026 (upto 09:00 P.M.) Last date of successful transaction of fee 08 March 2026 through Credit/Debit Card/Net-Banking/UPI (upto 11:50 P.M.) Correction in Particulars 10 March 2026 to 12 March 2026 Announcement of City Intimation To be announced later on the website Downloading of Admit Cards from the N",
      "Online Submission of Application Form 08 February 2026 to 08 March 2026",
      "Date of Examination 03 May 2026 (Sunday) Duration of Examination ",
      "NTA will take necessary action to make corrections in the record later. Note: a. The candidate may note that Admit Card will not be sent by post. b. In no case, the duplicate Admit Card for NEET (UG)-2026 would be issued at the Examination Centres. c. The candidate must not mutilate the Admit Card or change any entry made therein. d. Candidates are advised to preserve their Admit Card in good condition for future ref",
      "Correction in Particulars 10 March 2026 to 12 March 2026",
      "Qualifications for MBBS and BDS Course 1 Eligibility to Appear in NEET (UG)-2026 25 2 Criteria for NRI/OCI/ Foreign Nationals 25 3 Qualification and Qualifying examination codes 26 Chapter 7: Counselling and Reservation for Admission to MBBS, BAMS, BUMS, BSMS, BHMS, BDS and B",
      "Citizenship 92 (For Foreign and OCI Candidates) 8 VIII Procedure for Online Payment of Fee and Helpline for Payment 93 Related Queries 9 IX Replica of Application Form 96 10 X Important Points to Note 109 S",
      "Domicile) E. AMU Open & Internal seats F. 85% Internal quota/domicile seats of DU/ I"
    ],
    "sourceTitle": "Public Notices",
    "dataCertainty": "tentative",
    "applicationStatus": "closed",
    "refreshedThisCycle": false,
    "stale": true
  },
  "neet-ug-2026": {
    "lastDate": "08 March 2026",
    "applicationDates": "08 February 2026 to 08 March 2026",
    "examDate": "03 May 2026",
    "vacancies": "2026 notified",
    "correctionDates": "Correction in Particulars 10 March 2026 to 12 March 2026",
    "qualification": "a for NRI/OCI/ Foreign Nationals 25 3 Qualification and Qualifying examination codes 26 Chapter 7: Counselling and Reservation for Admission to MBBS, BAMS, BUMS, BSMS, BHMS, BDS and B",
    "nationality": "ure for Online Payment of Fee and Helpline for Payment 93 Related Queries 9 IX Replica of Application Form 96 10 X Important Points to Note 109 S",
    "domicile": "e seats of DU/ I",
    "slug": "neet-ug-2026",
    "cycleSlug": "neet-ug-2026",
    "name": "NEET UG 2026",
    "organization": "NTA",
    "notificationUrl": "https://cdnbbsr.s3waas.gov.in/s37bc1ec1d9c3426357e69acd5bf320061/uploads/2026/02/202602081576322299.pdf",
    "sourceUrl": "https://www.nta.ac.in/NoticeBoardArchive",
    "lastVerified": "2026-10-05",
    "detectedAt": "2026-10-05",
    "confidence": "high",
    "evidenceCount": 8,
    "evidence": [
      "lastDate",
      "applicationDates",
      "examDate",
      "vacancies",
      "correctionDates",
      "qualification",
      "nationality",
      "domicile"
    ],
    "evidenceSnippets": [
      "NT INFORMATION AND DATES AT A GLANCE EVENTS DATES Online Submission of Application Form 08 February 2026 to 08 March 2026 (upto 09:00 P.M.) Last date of successful transaction of fee 08 March 2026 through Credit/Debit Card/Net-Banking/UPI (upto 11:50 P.M.) Correction in Particulars 10 March 2026 to 12 March 2026 Announcement of City Intimation To be announced later on the website Downloading of Admit Cards from the N",
      "Online Submission of Application Form 08 February 2026 to 08 March 2026",
      "Date of Examination 03 May 2026 (Sunday) Duration of Examination ",
      "NTA will take necessary action to make corrections in the record later. Note: a. The candidate may note that Admit Card will not be sent by post. b. In no case, the duplicate Admit Card for NEET (UG)-2026 would be issued at the Examination Centres. c. The candidate must not mutilate the Admit Card or change any entry made therein. d. Candidates are advised to preserve their Admit Card in good condition for future ref",
      "Correction in Particulars 10 March 2026 to 12 March 2026",
      "Qualifications for MBBS and BDS Course 1 Eligibility to Appear in NEET (UG)-2026 25 2 Criteria for NRI/OCI/ Foreign Nationals 25 3 Qualification and Qualifying examination codes 26 Chapter 7: Counselling and Reservation for Admission to MBBS, BAMS, BUMS, BSMS, BHMS, BDS and B",
      "Citizenship 92 (For Foreign and OCI Candidates) 8 VIII Procedure for Online Payment of Fee and Helpline for Payment 93 Related Queries 9 IX Replica of Application Form 96 10 X Important Points to Note 109 S",
      "Domicile) E. AMU Open & Internal seats F. 85% Internal quota/domicile seats of DU/ I"
    ],
    "sourceTitle": "Final Opportunity to Confirm/Update Bank Account Details for NEET (UG) 2026 Fee Refund (Exam held on 03 May 2026)",
    "dataCertainty": "tentative",
    "applicationStatus": "closed",
    "refreshedThisCycle": false,
    "stale": true
  },
  "ctet-2026": {
    "examDate": "12 and 13 December 2026",
    "qualification": "of the post for which the examination is being conducted",
    "slug": "ctet-2026",
    "cycleSlug": "ctet-2026",
    "name": "CTET 2026",
    "organization": "CBSE",
    "notificationUrl": "https://ctet.nic.in/document/public-notice-exam-dates-for-22nd-edition-of-ctet/",
    "sourceUrl": "https://ctet.nic.in/",
    "lastVerified": "2026-10-06",
    "detectedAt": "2026-10-06",
    "confidence": "high",
    "evidenceCount": 5,
    "evidence": [
      "examDate",
      "qualification",
      "revisedExamDate",
      "reopenedApplicationWindow",
      "correctionWindow"
    ],
    "evidenceSnippets": [
      "examination at the assigned examination centre for ascertaining its suitability. f. As per office memorandum F. No. 29-6/2019-DD-III dated ",
      "qualification of the scribe would be one class lower than the minimum qualification criteria of the post for which the examination is being conducted",
      "CBSE public notice dated 14 September 2026: 22nd edition of CTET will be conducted on 12th and 13th December 2026.",
      "CTET reopened online application window: 25 August 2026 to 01 September 2026.",
      "CTET correction window: 07 September 2026 to 10 September 2026.",
      "CBSE public notice dated 14 September 2026: 22nd edition of CTET will be conducted on 12th and 13th December 2026.",
      "CTET reopened online application window: 25 August 2026 to 01 September 2026.",
      "CTET correction window: 07 September 2026 to 10 September 2026."
    ],
    "sourceTitle": "PUBLIC NOTICE: Exam Dates for 22nd edition of CTET",
    "dataCertainty": "confirmed",
    "applicationStatus": "unknown",
    "refreshedThisCycle": true,
    "applicationDates": "25 August 2026 to 01 September 2026",
    "lastDate": "01 September 2026",
    "correctionDates": "07 September 2026 to 10 September 2026",
    "stale": false
  },
  "india-post-gds-2025": {
    "lastDate": "16.05.2025",
    "qualification": "Table-II # Name of the post Minimum Essential Qualification(s) 1 Full time Factory Minimum MBBS with completed internship and registration Medical Officer on with Medical Council of India and must have Certificate of temporary tenure basis training in Industri",
    "selectionProcess": ", for which a separate communication will be issued to the concerned candidate",
    "slug": "india-post-gds-2025",
    "cycleSlug": "india-post-gds-2025",
    "familySlug": "family-india-post-gds",
    "cycleYear": 2025,
    "name": "India Post Gramin Dak Sevak 2025",
    "organization": "India Post",
    "notificationUrl": "https://www.gailonline.com/careers/currentOpnning/DETAILED_ADVERTISEMENT_29_05_2025.pdf",
    "sourceUrl": "https://www.gailonline.com/Vacancies.html",
    "lastVerified": "2026-10-05",
    "detectedAt": "2026-10-05",
    "confidence": "high",
    "evidenceCount": 3,
    "evidence": [
      "lastDate",
      "qualification",
      "selectionProcess"
    ],
    "evidenceSnippets": [
      "hemselves updated. 8.14 IMPORTANT DATES # Activity Date 1 Commencement of forwarding of application by candidates 30.04.2025 (11.00 hrs.) 2 Last date for forwarding of application by candidates 16.05.2025 (17.00 hrs.) 9. IMPORTANT INSTRUCTIONS 9.1 We hereby caution the general public not to fall prey to the dubious agencies/organizations/individuals/aiming at fleecing money from the innocent public. Don’t believe any",
      "Essential Qualification(s) for the above posts shall be as indicated in Table-II below: Table-II # Name of the post Minimum Essential Qualification(s) 1 Full time Factory Minimum MBBS with completed internship and registration Medical Officer on with Medical Council of India and must have Certificate of temporary tenure basis training in Industri",
      "Selection Process, he/ she has to bring the original application form with all ORIGINAL DOCUMENTS, for which a separate communication will be issued to the concerned candidate"
    ],
    "sourceTitle": "Detailed Advertisement PDF (103 KB)",
    "dataCertainty": "tentative",
    "applicationStatus": "closed",
    "refreshedThisCycle": false,
    "stale": true
  }
};
