// AUTO-GENERATED by scripts/discover-official-notices.mjs.
export const discoveredOfficialNotices = [] as const;
export const discoveryMeta = {
  generatedAt: "not-run-yet",
  registeredSources: 0,
  checkedSources: 0,
  discoveredItems: 0,
} as const;
