import {autoNotifications} from "./auto-notifications";

export type NotificationItem={
 id:string; title:string; organization:string; category:string; stage:"Application Open"|"Upcoming"|"Admit Card"|"Answer Key"|"Result"|"Recruitment";
 status:"Verified official"|"Auto-detected official link"; publishedDate:string; lastChecked:string; applicationLastDate?:string; examDate?:string; vacancies?:string; qualification?:string;
 officialUrl:string; notificationUrl?:string; applyUrl?:string; description:string;
};

export const notifications:NotificationItem[]=[
 {id:"ssc-cgl-2026-vacancy",title:"SSC CGL 2026 — Tentative Vacancy Update",organization:"Staff Selection Commission",category:"Central Government",stage:"Recruitment",status:"Verified official",publishedDate:"2026-09-24",lastChecked:"2026-09-27",officialUrl:"https://ssc.gov.in/",notificationUrl:"https://ssc.gov.in/",description:"SSC has published a tentative vacancy update for CGL 2026. Use the latest SSC notice/PDF for post-wise vacancy and reservation details; figures can be revised."},
 {id:"ibps-rrb-xv-vacancy",title:"IBPS RRB XV — Updated Vacancies",organization:"IBPS",category:"Banking",stage:"Recruitment",status:"Verified official",publishedDate:"2026-09-15",lastChecked:"2026-09-27",officialUrl:"https://www.ibps.in/index.php/crp-updates/",notificationUrl:"https://www.ibps.in/index.php/crp-updates/",description:"IBPS published updated vacancies for CRP-RRBs-XV on 15 September 2026. Check the official recruitment notice and updated vacancy document for post and state details."}, {id:"upsc-ese-2027",title:"Engineering Services (Preliminary) Examination, 2027",organization:"UPSC",category:"Engineering",stage:"Application Open",status:"Verified official",publishedDate:"2026-09-16",lastChecked:"2026-09-27",applicationLastDate:"2026-10-06 6:00 PM",examDate:"2027-01-31",qualification:"Engineering degree / prescribed qualification",officialUrl:"https://www.upsc.gov.in/examinations/Engineering%20Services%20%28Preliminary%29%20Examination%2C%202027",notificationUrl:"https://www.upsc.gov.in/exams-related-info/exam-notification",applyUrl:"https://upsconline.nic.in",description:"Official UPSC examination notification. Check the notice for branch-wise eligibility, age, fee and other conditions before applying."},
 {id:"upsc-so-steno-2026",title:"Combined Section Officers (Grade-B) LDCE 2026 & Stenographers LDCE",organization:"UPSC",category:"Central Government",stage:"Application Open",status:"Verified official",publishedDate:"2026-09-16",lastChecked:"2026-09-27",applicationLastDate:"2026-10-06 6:00 PM",examDate:"2026-12-12",qualification:"Departmental eligibility as prescribed",officialUrl:"https://www.upsc.gov.in/exams-related-info/exam-notification",notificationUrl:"https://www.upsc.gov.in/exams-related-info/exam-notification",applyUrl:"https://upsconline.nic.in",description:"Official UPSC notification listing. Eligibility is limited to the departmental candidates covered by the notice."},
 {id:"upsc-active-2026",title:"UPSC Active Examinations — official tracker",organization:"UPSC",category:"Civil Services",stage:"Upcoming",status:"Verified official",publishedDate:"2026-09-27",lastChecked:"2026-09-27",officialUrl:"https://www.upsc.gov.in/examinations/active-exams",description:"Official UPSC active-examinations index covering current examination cycles, including CSE Main 2026, CDS II 2026, NDA II 2026, CMS 2026 and CAPF 2026."},
 {id:"ssc-calendar-2026-27",title:"SSC Tentative Examination Calendar 2026–27",organization:"Staff Selection Commission",category:"Central Government",stage:"Upcoming",status:"Verified official",publishedDate:"2026-01-08",lastChecked:"2026-09-27",officialUrl:"https://ssc.gov.in/api/attachment/uploads/masterData/ExamCalendar/Tentative_Calendar2026_27_08012026.pdf",description:"Official SSC tentative calendar. It provides advertisement, closing and tentative examination periods; dates can change, so check the latest SSC notice before acting."}
];