import { exams, type Exam } from "@/lib/exams";

export type SeoLanding = {
  slug: string;
  title: string;
  description: string;
  h1: string;
  intro: string;
  keywords: string[];
  filter: (exam: Exam) => boolean;
};

const has = (exam: Exam, text: string) =>
  [exam.name, exam.organization, exam.category, exam.qualifications].join(" ").toLowerCase().includes(text.toLowerCase());

export const seoLandings: SeoLanding[] = [
  { slug: "government-jobs", title: "Government Jobs in India 2026", description: "Explore government job and recruitment routes across India by qualification, department and exam, with official-source links.", h1: "Government Jobs in India", intro: "Explore major government recruitment routes in one place. Use each exam guide to check qualification, age, cycle status and the latest official notification.", keywords: ["government jobs", "sarkari naukri", "government recruitment"], filter: () => true },
  { slug: "upcoming-government-exams", title: "Upcoming Government Exams 2026", description: "Find upcoming government exams in India across UPSC, SSC, banking, railway, defence, teaching, medical and state recruitment.", h1: "Upcoming Government Exams 2026", intro: "Find exam and recruitment cycles that are upcoming or scheduled in the SarkariPrep catalogue. Always verify the latest date on the linked official notification.", keywords: ["upcoming government exams 2026", "government exams 2026"], filter: e => isUpcomingExam(e) },
  { slug: "jobs-after-10th", title: "Government Jobs After 10th Pass 2026", description: "Government job and recruitment routes after 10th pass, including railway, SSC, police, defence and India Post pathways.", h1: "Government Jobs After 10th Pass", intro: "These routes are relevant to students who have completed Class 10. Post-specific age, subjects, physical standards and other conditions must be checked in the latest notification.", keywords: ["government jobs after 10th", "sarkari jobs 10th pass"], filter: e => /10th/i.test(e.qualifications) },
  { slug: "jobs-after-12th", title: "Government Jobs After 12th Pass 2026", description: "Explore government exams and recruitment routes for 12th-pass candidates, including SSC, railway, defence and teaching pathways.", h1: "Government Jobs After 12th Pass", intro: "Explore major 10+2-level routes. Some exams have stream, subject, age or post-specific requirements, so use the official notification as the final authority.", keywords: ["government jobs after 12th", "sarkari jobs 12th pass"], filter: e => /12th|10+2/i.test(e.qualifications) },
  { slug: "jobs-after-graduation", title: "Government Jobs After Graduation 2026", description: "Find government exams and recruitment routes after graduation, including UPSC, SSC, banking, railway and state PSC pathways.", h1: "Government Jobs After Graduation", intro: "Graduation opens a wide range of central and state recruitment routes. Compare exam families and open the dedicated guide for eligibility and official sources.", keywords: ["government jobs after graduation", "graduate government jobs"], filter: e => /graduate|bachelor|postgraduate|master/i.test(e.qualifications) },
  { slug: "engineering-government-jobs", title: "Engineering Government Jobs & Exams 2026", description: "Explore engineering government exams and recruitment routes including ESE, SSC JE, RRB JE, GATE and PSU pathways.", h1: "Engineering Government Jobs & Exams", intro: "Engineering candidates can explore central, railway, PSU and state routes. Branch-specific eligibility varies, so verify the latest notification before applying.", keywords: ["engineering government jobs", "government jobs for engineers", "SSC JE", "RRB JE"], filter: e => e.category === "Engineering" || /engineering|diploma/i.test(e.qualifications) },
  { slug: "banking-government-jobs", title: "Banking Government Exams & Jobs 2026", description: "Explore banking recruitment routes including IBPS, SBI, RBI, NABARD, SEBI and insurance-sector exams with official links.", h1: "Banking Government Exams & Jobs", intro: "Explore major public-sector banking and financial recruitment routes. Open each guide for qualification, age and official recruitment information.", keywords: ["banking exams 2026", "bank government jobs", "IBPS", "SBI"], filter: e => e.category === "Banking" || /banking|bank|RBI|NABARD|SEBI/i.test(e.organization + " " + e.name) },
  { slug: "railway-government-jobs", title: "Railway Government Jobs & Exams 2026", description: "Explore railway recruitment routes including RRB NTPC, Group D, JE, ALP, Technician, RPF and other railway pathways.", h1: "Railway Government Jobs & Exams", intro: "Explore Railway Recruitment Board pathways by qualification and role. Current vacancies and dates are cycle-specific and should be checked against the latest official notice.", keywords: ["railway jobs 2026", "RRB exams 2026", "railway government jobs"], filter: e => e.category === "Railway" || /railway|RRB|RPF/i.test(e.organization + " " + e.name) },
  { slug: "defence-government-jobs", title: "Defence Government Jobs & Exams 2026", description: "Explore defence recruitment and exams including NDA, CDS, CAPF, AFCAT, Agniveer and Coast Guard pathways.", h1: "Defence Government Jobs & Exams", intro: "Explore officer and other defence recruitment pathways. Physical, medical, age, education and branch conditions can differ significantly by notification.", keywords: ["defence jobs 2026", "defence exams 2026", "NDA", "CDS"], filter: e => e.category === "Defence" || /defence|army|navy|air force|AFCAT|NDA|CDS|CAPF/i.test(e.organization + " " + e.name) },
  { slug: "teaching-government-jobs", title: "Teaching Government Exams & Jobs 2026", description: "Explore teaching and academic eligibility routes including CTET, UGC NET, CSIR NET and related recruitment pathways.", h1: "Teaching Government Exams & Jobs", intro: "Explore teaching and academic eligibility routes. Recruitment after an eligibility test can be handled by separate authorities, so check the relevant vacancy notification.", keywords: ["teaching government jobs", "teacher exams 2026", "CTET", "UGC NET"], filter: e => e.category === "Teaching" || /teaching|CTET|NET/i.test(e.organization + " " + e.name) },
  { slug: "medical-government-exams", title: "Medical Government Exams & Recruitment 2026", description: "Explore medical entrance, recruitment and postgraduate pathways including NEET, NEET PG, CMS, INI-CET and AIIMS routes.", h1: "Medical Government Exams & Recruitment", intro: "Explore medical examination and recruitment pathways. Admission and recruitment rules are controlled by their respective official authorities.", keywords: ["medical government jobs", "medical exams 2026", "NEET PG", "CMS"], filter: e => e.category === "Medical" || /medical|MBBS|NEET|AIIMS|CMS/i.test(e.organization + " " + e.name + " " + e.qualifications) },
  { slug: "jharkhand-government-jobs", title: "Jharkhand Government Jobs & Exams 2026", description: "Explore Jharkhand government recruitment routes including JPSC, JSSC and other state-level opportunities.", h1: "Jharkhand Government Jobs & Exams", intro: "Explore Jharkhand-focused recruitment routes available in the SarkariPrep catalogue. Always check the latest JPSC, JSSC or recruiting-authority notification for current-cycle details.", keywords: ["Jharkhand government jobs 2026", "JPSC", "JSSC"], filter: e => /JPSC|JSSC|Jharkhand/i.test(e.organization + " " + e.name) }
];

export function getSeoLanding(slug: string) {
  return seoLandings.find(x => x.slug === slug);
}

export function getLandingExams(landing: SeoLanding) {
  return exams.filter(landing.filter);
}
