export type SourceStatus = {id:string; organization:string; category:string; region:string; sourceUrl:string; ok:boolean; detected:number; lastChecked:string; error?:string};

export const sourceStatuses:Record<string,SourceStatus> = {
  "upsc": {
    "id": "upsc",
    "organization": "UPSC",
    "category": "Central Government",
    "region": "Central",
    "sourceUrl": "https://www.upsc.gov.in/whats-new",
    "ok": true,
    "detected": 55,
    "lastChecked": "2026-09-27"
  },
  "ssc": {
    "id": "ssc",
    "organization": "Staff Selection Commission",
    "category": "Central Government",
    "region": "Central",
    "sourceUrl": "https://ssc.gov.in/",
    "ok": true,
    "detected": 0,
    "lastChecked": "2026-09-27"
  },
  "ibps": {
    "id": "ibps",
    "organization": "IBPS",
    "category": "Banking",
    "region": "Central",
    "sourceUrl": "https://www.ibps.in/index.php/crp-updates/",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "TypeError: fetch failed"
  },
  "nta": {
    "id": "nta",
    "organization": "National Testing Agency",
    "category": "Entrance / Eligibility",
    "region": "Central",
    "sourceUrl": "https://www.nta.ac.in/NoticeBoardArchive",
    "ok": true,
    "detected": 66,
    "lastChecked": "2026-09-27"
  },
  "ctet": {
    "id": "ctet",
    "organization": "CTET",
    "category": "Teaching",
    "region": "Central",
    "sourceUrl": "https://ctet.nic.in/",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "TypeError: fetch failed"
  },
  "railways": {
    "id": "railways",
    "organization": "Indian Railways / RRB",
    "category": "Railway",
    "region": "Central",
    "sourceUrl": "https://indianrailways.gov.in/",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "TypeError: fetch failed"
  },
  "rbi": {
    "id": "rbi",
    "organization": "Reserve Bank of India",
    "category": "Banking",
    "region": "Central",
    "sourceUrl": "https://opportunities.rbi.org.in/",
    "ok": true,
    "detected": 0,
    "lastChecked": "2026-09-27"
  },
  "sbi": {
    "id": "sbi",
    "organization": "State Bank of India",
    "category": "Banking",
    "region": "Central",
    "sourceUrl": "https://sbi.co.in/web/careers",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "TypeError: fetch failed"
  },
  "lic": {
    "id": "lic",
    "organization": "LIC",
    "category": "Insurance",
    "region": "Central",
    "sourceUrl": "https://licindia.in/careers",
    "ok": true,
    "detected": 5,
    "lastChecked": "2026-09-27"
  },
  "epfo": {
    "id": "epfo",
    "organization": "EPFO",
    "category": "Central Government",
    "region": "Central",
    "sourceUrl": "https://www.epfindia.gov.in/site_en/Recruitments.php",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "Error: HTTP 403"
  },
  "isro": {
    "id": "isro",
    "organization": "ISRO",
    "category": "Science & Engineering",
    "region": "Central",
    "sourceUrl": "https://www.isro.gov.in/Careers.html",
    "ok": true,
    "detected": 18,
    "lastChecked": "2026-09-27"
  },
  "drdo": {
    "id": "drdo",
    "organization": "DRDO",
    "category": "Science & Engineering",
    "region": "Central",
    "sourceUrl": "https://www.drdo.gov.in/careers",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "Error: HTTP 404"
  },
  "aiims": {
    "id": "aiims",
    "organization": "AIIMS",
    "category": "Medical",
    "region": "Central",
    "sourceUrl": "https://www.aiimsexams.ac.in/",
    "ok": true,
    "detected": 5,
    "lastChecked": "2026-09-27"
  },
  "esic": {
    "id": "esic",
    "organization": "ESIC",
    "category": "Medical",
    "region": "Central",
    "sourceUrl": "https://www.esic.gov.in/recruitments",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "TypeError: fetch failed"
  },
  "indiapost": {
    "id": "indiapost",
    "organization": "India Post",
    "category": "Central Government",
    "region": "Central",
    "sourceUrl": "https://indiapost.gov.in/gdsonlineengagement",
    "ok": true,
    "detected": 1,
    "lastChecked": "2026-09-27"
  },
  "employment-news": {
    "id": "employment-news",
    "organization": "Employment News",
    "category": "Government Jobs",
    "region": "Central",
    "sourceUrl": "https://employmentnews.gov.in/",
    "ok": true,
    "detected": 0,
    "lastChecked": "2026-09-27"
  },
  "andhra-pradesh-psc": {
    "id": "andhra-pradesh-psc",
    "organization": "Andhra Pradesh Public Service Commission",
    "category": "State Government",
    "region": "Andhra Pradesh",
    "sourceUrl": "https://psc.ap.gov.in/",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "TypeError: fetch failed"
  },
  "arunachal-pradesh-psc": {
    "id": "arunachal-pradesh-psc",
    "organization": "Arunachal Pradesh Public Service Commission",
    "category": "State Government",
    "region": "Arunachal Pradesh",
    "sourceUrl": "https://appsc.gov.in/",
    "ok": true,
    "detected": 25,
    "lastChecked": "2026-09-27"
  },
  "assam-psc": {
    "id": "assam-psc",
    "organization": "Assam Public Service Commission",
    "category": "State Government",
    "region": "Assam",
    "sourceUrl": "https://apsc.nic.in/",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "TypeError: fetch failed"
  },
  "bihar-psc": {
    "id": "bihar-psc",
    "organization": "Bihar Public Service Commission",
    "category": "State Government",
    "region": "Bihar",
    "sourceUrl": "https://bpsc.bihar.gov.in/",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "TypeError: fetch failed"
  },
  "chhattisgarh-psc": {
    "id": "chhattisgarh-psc",
    "organization": "Chhattisgarh Public Service Commission",
    "category": "State Government",
    "region": "Chhattisgarh",
    "sourceUrl": "https://psc.cg.gov.in/",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "TypeError: fetch failed"
  },
  "goa-psc": {
    "id": "goa-psc",
    "organization": "Goa Public Service Commission",
    "category": "State Government",
    "region": "Goa",
    "sourceUrl": "https://gpsc.goa.gov.in/",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "Error: HTTP 403"
  },
  "gujarat-psc": {
    "id": "gujarat-psc",
    "organization": "Gujarat Public Service Commission",
    "category": "State Government",
    "region": "Gujarat",
    "sourceUrl": "https://gpsc.gujarat.gov.in/",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "TypeError: fetch failed"
  },
  "haryana-psc": {
    "id": "haryana-psc",
    "organization": "Haryana Public Service Commission",
    "category": "State Government",
    "region": "Haryana",
    "sourceUrl": "https://hpsc.gov.in/",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "TypeError: fetch failed"
  },
  "himachal-psc": {
    "id": "himachal-psc",
    "organization": "Himachal Pradesh Public Service Commission",
    "category": "State Government",
    "region": "Himachal Pradesh",
    "sourceUrl": "https://hppsc.hp.gov.in/",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "TypeError: fetch failed"
  },
  "jk-psc": {
    "id": "jk-psc",
    "organization": "Jammu & Kashmir Public Service Commission",
    "category": "State/UT Government",
    "region": "Jammu & Kashmir",
    "sourceUrl": "https://jkpsc.nic.in/",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "TypeError: fetch failed"
  },
  "jharkhand-psc": {
    "id": "jharkhand-psc",
    "organization": "Jharkhand Public Service Commission",
    "category": "State Government",
    "region": "Jharkhand",
    "sourceUrl": "https://www.jpsc.gov.in/",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "TypeError: fetch failed"
  },
  "karnataka-psc": {
    "id": "karnataka-psc",
    "organization": "Karnataka Public Service Commission",
    "category": "State Government",
    "region": "Karnataka",
    "sourceUrl": "https://kpsc.kar.nic.in/",
    "ok": true,
    "detected": 0,
    "lastChecked": "2026-09-27"
  },
  "kerala-psc": {
    "id": "kerala-psc",
    "organization": "Kerala Public Service Commission",
    "category": "State Government",
    "region": "Kerala",
    "sourceUrl": "https://www.keralapsc.gov.in/",
    "ok": true,
    "detected": 15,
    "lastChecked": "2026-09-27"
  },
  "madhya-pradesh-psc": {
    "id": "madhya-pradesh-psc",
    "organization": "Madhya Pradesh Public Service Commission",
    "category": "State Government",
    "region": "Madhya Pradesh",
    "sourceUrl": "https://mppsc.mp.gov.in/",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "TypeError: fetch failed"
  },
  "maharashtra-psc": {
    "id": "maharashtra-psc",
    "organization": "Maharashtra Public Service Commission",
    "category": "State Government",
    "region": "Maharashtra",
    "sourceUrl": "https://mpsc.gov.in/",
    "ok": true,
    "detected": 0,
    "lastChecked": "2026-09-27"
  },
  "manipur-psc": {
    "id": "manipur-psc",
    "organization": "Manipur Public Service Commission",
    "category": "State Government",
    "region": "Manipur",
    "sourceUrl": "https://mpscmanipur.gov.in/",
    "ok": true,
    "detected": 12,
    "lastChecked": "2026-09-27"
  },
  "meghalaya-psc": {
    "id": "meghalaya-psc",
    "organization": "Meghalaya Public Service Commission",
    "category": "State Government",
    "region": "Meghalaya",
    "sourceUrl": "https://mpsc.meghalaya.gov.in/",
    "ok": true,
    "detected": 80,
    "lastChecked": "2026-09-27"
  },
  "mizoram-psc": {
    "id": "mizoram-psc",
    "organization": "Mizoram Public Service Commission",
    "category": "State Government",
    "region": "Mizoram",
    "sourceUrl": "https://mpsc.mizoram.gov.in/",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "Error: HTTP 403"
  },
  "nagaland-psc": {
    "id": "nagaland-psc",
    "organization": "Nagaland Public Service Commission",
    "category": "State Government",
    "region": "Nagaland",
    "sourceUrl": "https://npsc.nagaland.gov.in/",
    "ok": true,
    "detected": 17,
    "lastChecked": "2026-09-27"
  },
  "odisha-psc": {
    "id": "odisha-psc",
    "organization": "Odisha Public Service Commission",
    "category": "State Government",
    "region": "Odisha",
    "sourceUrl": "https://www.opsc.gov.in/",
    "ok": true,
    "detected": 7,
    "lastChecked": "2026-09-27"
  },
  "punjab-psc": {
    "id": "punjab-psc",
    "organization": "Punjab Public Service Commission",
    "category": "State Government",
    "region": "Punjab",
    "sourceUrl": "https://www.ppsc.gov.in/",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "TypeError: fetch failed"
  },
  "rajasthan-psc": {
    "id": "rajasthan-psc",
    "organization": "Rajasthan Public Service Commission",
    "category": "State Government",
    "region": "Rajasthan",
    "sourceUrl": "https://rpsc.rajasthan.gov.in/",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "TypeError: fetch failed"
  },
  "sikkim-psc": {
    "id": "sikkim-psc",
    "organization": "Sikkim Public Service Commission",
    "category": "State Government",
    "region": "Sikkim",
    "sourceUrl": "https://spsc.sikkim.gov.in/",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "TypeError: fetch failed"
  },
  "tamil-nadu-psc": {
    "id": "tamil-nadu-psc",
    "organization": "Tamil Nadu Public Service Commission",
    "category": "State Government",
    "region": "Tamil Nadu",
    "sourceUrl": "https://www.tnpsc.gov.in/",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "TypeError: fetch failed"
  },
  "telangana-psc": {
    "id": "telangana-psc",
    "organization": "Telangana Public Service Commission",
    "category": "State Government",
    "region": "Telangana",
    "sourceUrl": "https://www.tspsc.gov.in/",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "TypeError: fetch failed"
  },
  "tripura-psc": {
    "id": "tripura-psc",
    "organization": "Tripura Public Service Commission",
    "category": "State Government",
    "region": "Tripura",
    "sourceUrl": "https://tpsc.tripura.gov.in/",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "TypeError: fetch failed"
  },
  "uttar-pradesh-psc": {
    "id": "uttar-pradesh-psc",
    "organization": "Uttar Pradesh Public Service Commission",
    "category": "State Government",
    "region": "Uttar Pradesh",
    "sourceUrl": "https://uppsc.up.nic.in/",
    "ok": true,
    "detected": 18,
    "lastChecked": "2026-09-27"
  },
  "uttarakhand-psc": {
    "id": "uttarakhand-psc",
    "organization": "Uttarakhand Public Service Commission",
    "category": "State Government",
    "region": "Uttarakhand",
    "sourceUrl": "https://psc.uk.gov.in/",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "TypeError: fetch failed"
  },
  "west-bengal-psc": {
    "id": "west-bengal-psc",
    "organization": "West Bengal Public Service Commission",
    "category": "State Government",
    "region": "West Bengal",
    "sourceUrl": "https://psc.wb.gov.in/",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "TypeError: fetch failed"
  },
  "ncs": {
    "id": "ncs",
    "organization": "National Career Service",
    "category": "Government Jobs",
    "region": "All India",
    "sourceUrl": "https://ncs.gov.in/devPortalList",
    "ok": true,
    "detected": 5,
    "lastChecked": "2026-09-27"
  },
  "india-gov-directory": {
    "id": "india-gov-directory",
    "organization": "National Portal of India",
    "category": "Government Directory",
    "region": "All India",
    "sourceUrl": "https://www.india.gov.in/directory/public-utilities",
    "ok": true,
    "detected": 1,
    "lastChecked": "2026-09-27"
  },
  "jharkhand-recruitment": {
    "id": "jharkhand-recruitment",
    "organization": "Jharkhand Government Recruitment Portal",
    "category": "State Government",
    "region": "Jharkhand",
    "sourceUrl": "https://recruitment.jharkhand.gov.in/",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "TypeError: fetch failed"
  },
  "delhi-employment": {
    "id": "delhi-employment",
    "organization": "Delhi Employment Portal",
    "category": "State/UT Government",
    "region": "Delhi",
    "sourceUrl": "https://onlineemploymentportal.delhi.gov.in/",
    "ok": true,
    "detected": 0,
    "lastChecked": "2026-09-27"
  },
  "gujarat-employment": {
    "id": "gujarat-employment",
    "organization": "Gujarat Employment Portal",
    "category": "State Government",
    "region": "Gujarat",
    "sourceUrl": "https://anubandham.gujarat.gov.in/",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "TypeError: fetch failed"
  },
  "haryana-employment": {
    "id": "haryana-employment",
    "organization": "Haryana Employment Portal",
    "category": "State Government",
    "region": "Haryana",
    "sourceUrl": "https://www.hrex.gov.in/",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "TypeError: fetch failed"
  },
  "himachal-employment": {
    "id": "himachal-employment",
    "organization": "Himachal Pradesh Employment Portal",
    "category": "State Government",
    "region": "Himachal Pradesh",
    "sourceUrl": "https://eemis.hp.gov.in/",
    "ok": true,
    "detected": 9,
    "lastChecked": "2026-09-27"
  },
  "jk-employment": {
    "id": "jk-employment",
    "organization": "Jammu & Kashmir Employment Portal",
    "category": "State/UT Government",
    "region": "Jammu & Kashmir",
    "sourceUrl": "https://jakemp.nic.in/",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "TypeError: fetch failed"
  },
  "karnataka-employment": {
    "id": "karnataka-employment",
    "organization": "Karnataka Employment Wing",
    "category": "State Government",
    "region": "Karnataka",
    "sourceUrl": "https://itiemp.karnataka.gov.in/13/employment-wing/en",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "TypeError: fetch failed"
  },
  "kerala-employment": {
    "id": "kerala-employment",
    "organization": "Kerala Employment Portal",
    "category": "State Government",
    "region": "Kerala",
    "sourceUrl": "https://www.employment.kerala.gov.in/",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "TypeError: fetch failed"
  },
  "madhya-pradesh-employment": {
    "id": "madhya-pradesh-employment",
    "organization": "Madhya Pradesh Employment Portal",
    "category": "State Government",
    "region": "Madhya Pradesh",
    "sourceUrl": "https://mprojgar.gov.in/home",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "TypeError: fetch failed"
  },
  "maharashtra-employment": {
    "id": "maharashtra-employment",
    "organization": "Maharashtra Employment Portal",
    "category": "State Government",
    "region": "Maharashtra",
    "sourceUrl": "https://rojgar.mahaswayam.gov.in/#/home/index",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "Error: HTTP 403"
  },
  "odisha-employment": {
    "id": "odisha-employment",
    "organization": "Odisha Employment Portal",
    "category": "State Government",
    "region": "Odisha",
    "sourceUrl": "https://empmission.odisha.gov.in/Exchange/Entry.jsp",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "TypeError: fetch failed"
  },
  "punjab-employment": {
    "id": "punjab-employment",
    "organization": "Punjab Employment Portal",
    "category": "State Government",
    "region": "Punjab",
    "sourceUrl": "https://www.pgrkam.com/",
    "ok": true,
    "detected": 0,
    "lastChecked": "2026-09-27"
  },
  "rajasthan-employment": {
    "id": "rajasthan-employment",
    "organization": "Rajasthan Employment Portal",
    "category": "State Government",
    "region": "Rajasthan",
    "sourceUrl": "https://rajemployment.rajasthan.gov.in/",
    "ok": true,
    "detected": 0,
    "lastChecked": "2026-09-27"
  },
  "tamil-nadu-employment": {
    "id": "tamil-nadu-employment",
    "organization": "Tamil Nadu Employment Portal",
    "category": "State Government",
    "region": "Tamil Nadu",
    "sourceUrl": "https://tnvelaivaaippu.gov.in/",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "TypeError: fetch failed"
  },
  "uttar-pradesh-employment": {
    "id": "uttar-pradesh-employment",
    "organization": "Uttar Pradesh Employment Portal",
    "category": "State Government",
    "region": "Uttar Pradesh",
    "sourceUrl": "http://sewayojan.up.nic.in/",
    "ok": true,
    "detected": 3,
    "lastChecked": "2026-09-27"
  },
  "west-bengal-employment": {
    "id": "west-bengal-employment",
    "organization": "West Bengal Employment Bank",
    "category": "State Government",
    "region": "West Bengal",
    "sourceUrl": "https://employmentbankwb.gov.in/index.php",
    "ok": false,
    "detected": 0,
    "lastChecked": "2026-09-27",
    "error": "TypeError: fetch failed"
  }
};
