export type SyllabusTopic={subject:string;topics:string[]};
export type ExamSyllabus={slug:string;title:string;status:"official-structured"|"official-source";sourceUrl:string;lastVerified:string;subjects:SyllabusTopic[]};

export const syllabusBySlug:Record<string,ExamSyllabus>={

"ibps-po-2026":{slug:"ibps-po-2026",title:"IBPS PO/MT — structured syllabus",status:"official-structured",sourceUrl:"https://www.ibps.in/index.php/management-trainees-xv/",lastVerified:"2026-09-27",subjects:[{subject:"Prelims — English Language",topics:["Reading comprehension","Cloze test","Error detection","Sentence improvement","Fillers","Para jumbles","Vocabulary","Grammar"]},{subject:"Prelims — Quantitative Aptitude",topics:["Number series","Simplification","Approximation","Quadratic equations","Data interpretation","Percentage","Ratio","Average","Profit and loss","Time and work","Time and distance","Simple and compound interest","Probability and permutation-combination basics"]},{subject:"Prelims — Reasoning Ability",topics:["Puzzles","Seating arrangement","Syllogism","Inequality","Coding-decoding","Blood relations","Direction sense","Order and ranking","Alphanumeric series","Input-output","Data sufficiency"]},{subject:"Mains — Reasoning & Computer Aptitude",topics:["Advanced puzzles","Logical reasoning","Critical reasoning","Syllogism","Data sufficiency","Computer fundamentals","Operating systems","Networking","Internet","Cyber security"]},{subject:"Mains — Data Analysis & Interpretation",topics:["Caselet DI","Tabular DI","Bar/line/pie charts","Missing DI","Arithmetic","Data sufficiency","Probability","Permutation and combination"]},{subject:"Mains — Economy/Banking Awareness",topics:["Banking system","RBI","Monetary policy","Financial markets","Budget and economic survey","Banking terms","Current affairs","Government schemes","Financial inclusion"]},{subject:"Mains — English + Descriptive",topics:["Reading comprehension","Grammar","Vocabulary","Para completion","Precis","Essay","Letter writing"]}]},
"sbi-po-2026":{slug:"sbi-po-2026",title:"SBI PO — structured syllabus",status:"official-structured",sourceUrl:"https://sbi.co.in/web/careers/probationary-officers",lastVerified:"2026-09-27",subjects:[{subject:"Prelims — English Language",topics:["Reading comprehension","Cloze test","Error spotting","Fillers","Sentence rearrangement","Vocabulary","Grammar"]},{subject:"Prelims — Quantitative Aptitude",topics:["Simplification","Approximation","Number series","Quadratic equations","Data interpretation","Arithmetic"]},{subject:"Prelims — Reasoning Ability",topics:["Puzzles","Seating arrangement","Syllogism","Inequality","Coding-decoding","Blood relation","Direction","Ranking"]},{subject:"Mains — Reasoning & Computer Aptitude",topics:["Advanced reasoning","Puzzles","Logical reasoning","Data sufficiency","Computer fundamentals","Networking","Internet","Cyber security"]},{subject:"Mains — Data Analysis & Interpretation",topics:["Charts","Caselets","Missing data","Arithmetic","Probability","Permutation and combination"]},{subject:"Mains — Economy/Banking Awareness",topics:["Indian banking","RBI","Monetary policy","Financial awareness","Banking current affairs","Economy","Government schemes"]},{subject:"Mains — English Descriptive",topics:["Essay","Letter writing","Reading comprehension","Grammar and vocabulary"]}]},
"ibps-clerk-2026":{slug:"ibps-clerk-2026",title:"IBPS Customer Service Associate — structured syllabus",status:"official-structured",sourceUrl:"https://www.ibps.in/index.php/clerical-cadre-xv/",lastVerified:"2026-09-27",subjects:[{subject:"English Language",topics:["Reading comprehension","Cloze test","Error spotting","Fillers","Vocabulary","Grammar","Sentence rearrangement"]},{subject:"Numerical Ability",topics:["Simplification","Approximation","Number series","Quadratic equations","Data interpretation","Arithmetic"]},{subject:"Reasoning Ability",topics:["Puzzles","Seating arrangement","Syllogism","Inequality","Coding-decoding","Blood relations","Direction","Alphanumeric series"]},{subject:"General/Financial Awareness",topics:["Current affairs","Banking awareness","RBI","Financial institutions","Economy","Government schemes"]}]},
"rrb-ntpc-2026":{slug:"rrb-ntpc-2026",title:"RRB NTPC — structured syllabus",status:"official-structured",sourceUrl:"https://www.rrbcdg.gov.in/",lastVerified:"2026-09-27",subjects:[{subject:"Mathematics",topics:["Number system","Decimals","Fractions","LCM/HCF","Ratio","Percentage","Mensuration","Time and work","Time and distance","Simple and compound interest","Profit and loss","Algebra","Geometry","Trigonometry","Elementary statistics","Age","Calendar and clock","Pipes and cistern"]},{subject:"General Intelligence & Reasoning",topics:["Analogies","Number/alphabet series","Coding-decoding","Mathematical operations","Relationships","Syllogism","Venn diagrams","Data interpretation and sufficiency","Conclusions","Decision making","Similarities and differences","Analytical reasoning","Classification","Directions","Statement-argument-assumption"]},{subject:"General Awareness",topics:["Current affairs","Indian geography","Culture","Indian history and freedom movement","Indian polity and Constitution","Indian economy","Environmental issues","Sports","Scientific and technological developments"]},{subject:"General Science",topics:["Physics up to secondary level","Chemistry up to secondary level","Life sciences up to secondary level"]}]},
"rrb-group-d-2026":{slug:"rrb-group-d-2026",title:"RRB Group D — structured syllabus",status:"official-structured",sourceUrl:"https://www.rrbcdg.gov.in/",lastVerified:"2026-09-27",subjects:[{subject:"Mathematics",topics:["Number system","BODMAS","Decimals","Fractions","LCM/HCF","Ratio","Percentage","Mensuration","Time and work","Time and distance","Interest","Profit and loss","Algebra","Geometry","Trigonometry","Elementary statistics","Age","Calendar and clock","Pipes and cistern"]},{subject:"General Intelligence & Reasoning",topics:["Analogies","Series","Coding-decoding","Relationships","Syllogism","Venn diagram","Data interpretation","Conclusions","Classification","Directions","Statement-based reasoning"]},{subject:"General Science",topics:["Physics","Chemistry","Life science","Secondary-school level concepts"]},{subject:"General Awareness & Current Affairs",topics:["Science and technology","Sports","Culture","Personalities","Economics","Politics","Important events"]}]},\n"upsc-cse-2026":{slug:"upsc-cse-2026",title:"UPSC Civil Services Examination — structured syllabus",status:"official-structured",sourceUrl:"https://upsc.gov.in/examinations",lastVerified:"2026-09-27",subjects:[
{subject:"General Studies Paper I",topics:["Indian Heritage & Culture","History of India and Indian National Movement","Indian and World Geography — physical, social and economic","Indian Society and Diversity","Governance and Constitution","Polity and governance","Social justice and welfare","International relations","Economic and social development","Sustainable development","Poverty and inclusion","Demographics","General issues on environmental ecology, biodiversity and climate change","General science"]},
{subject:"General Studies Paper II — CSAT",topics:["Comprehension","Interpersonal and communication skills","Logical reasoning","Analytical ability","Decision making and problem solving","General mental ability","Basic numeracy","Data interpretation","Class X level mathematics"]},
{subject:"Civil Services Main — Essay",topics:["Essay writing","Multiple dimensions of a topic","Coherent argument and structure","Relevant examples and evidence","Concise expression"]},
{subject:"GS Paper I — Mains",topics:["Indian culture","Modern Indian history","Freedom struggle","Post-independence consolidation","World history","Indian society","Women and population issues","Urbanisation","Globalisation","Physical geography","Natural resources","Geophysical phenomena"]},
{subject:"GS Paper II — Mains",topics:["Constitution","Federalism","Parliament and state legislatures","Executive and judiciary","Constitutional bodies","Governance","Transparency and accountability","Civil services","Welfare schemes","Health and education","Poverty and hunger","International relations"]},
{subject:"GS Paper III — Mains",topics:["Indian economy","Inclusive growth","Government budgeting","Agriculture","Food processing","Land reforms","Infrastructure","Science and technology","Environment","Disaster management","Internal security","Cyber security","Money laundering","Border management"]},
{subject:"GS Paper IV — Ethics",topics:["Ethics and human interface","Human values","Attitude","Aptitude and foundational values","Emotional intelligence","Moral thinkers and philosophers","Public service values","Probity in governance","Codes of ethics","Case studies"]},
{subject:"Optional Subject",topics:["One UPSC-approved optional subject","Subject-specific Paper I","Subject-specific Paper II","Current official optional syllabus must be followed"]}]
},
"upsc-ese-2027":{slug:"upsc-ese-2027",title:"UPSC Engineering Services Examination — structured syllabus",status:"official-structured",sourceUrl:"https://www.upsc.gov.in/examinations/Engineering%20Services%20%28Preliminary%29%20Examination%2C%202027",lastVerified:"2026-09-27",subjects:[
{subject:"Paper I — General Studies & Engineering Aptitude",topics:["Current national and international issues relevant to engineering","Logical reasoning and analytical ability","Engineering mathematics and numerical analysis","General principles of design, drawing and safety","Standards and quality practices","Energy and environment","Basics of project management","Material science and engineering","ICT based tools and applications in engineering","Ethics and values in engineering profession"]},
{subject:"Civil Engineering",topics:["Engineering mechanics","Strength of materials","Structural analysis","Design of concrete and steel structures","Fluid mechanics","Hydraulics","Hydrology","Irrigation engineering","Geotechnical engineering","Foundation engineering","Transportation engineering","Environmental engineering","Surveying","Construction planning and management"]},
{subject:"Mechanical Engineering",topics:["Engineering mechanics","Mechanics of materials","Theory of machines","Machine design","Thermodynamics","Fluid mechanics","Heat transfer","IC engines","Refrigeration and air conditioning","Power plant engineering","Renewable energy","Production engineering","Industrial engineering and management","Engineering materials"]},
{subject:"Electrical Engineering",topics:["Circuit theory","Electrical and electronic measurements","Electrical machines","Power systems","Power electronics","Control systems","Electrical materials","Analog and digital electronics","Microprocessors and microcontrollers","Communication fundamentals","Utilization of electrical energy"]},
{subject:"Electronics & Telecommunication Engineering",topics:["Electronic devices and circuits","Digital electronics","Microprocessors and microcontrollers","Communication systems","Electromagnetic theory","Computer engineering","Signal processing","Control systems","Microwave engineering","Measurements and instrumentation","Network theory"]}]
},
"nda-ii-2026":{slug:"nda-ii-2026",title:"NDA & NA — structured syllabus",status:"official-structured",sourceUrl:"https://upsc.gov.in/examinations",lastVerified:"2026-09-27",subjects:[
{subject:"Mathematics",topics:["Algebra","Matrices and determinants","Trigonometry","Analytical geometry","Differential calculus","Integral calculus","Differential equations","Vector algebra","Statistics and probability"]},
{subject:"General Ability Test — English",topics:["Grammar and usage","Vocabulary","Comprehension","Cohesion and correct expression"]},
{subject:"General Ability Test — General Knowledge",topics:["Physics","Chemistry","General science","Social studies","History","Geography","Current events"]}]
},
"cds-ii-2026":{slug:"cds-ii-2026",title:"CDS — structured syllabus",status:"official-structured",sourceUrl:"https://upsc.gov.in/examinations",lastVerified:"2026-09-27",subjects:[
{subject:"English",topics:["Grammar","Vocabulary","Usage","Comprehension","Sentence arrangement","Error detection"]},
{subject:"General Knowledge",topics:["Current affairs","History","Geography","Polity","Economy","General science","Defence awareness"]},
{subject:"Elementary Mathematics",topics:["Arithmetic","Algebra","Trigonometry","Geometry","Mensuration","Statistics"]}]
},
"upsc-capf-2026":{slug:"upsc-capf-2026",title:"CAPF Assistant Commandants — structured syllabus",status:"official-structured",sourceUrl:"https://upsc.gov.in/examinations",lastVerified:"2026-09-27",subjects:[
{subject:"General Ability & Intelligence",topics:["Logical reasoning","Quantitative aptitude","Numerical ability","Data interpretation","General science","Current events","Indian polity","Economy","History","Geography"]},
{subject:"General Studies — Essay & Comprehension",topics:["Essay on security and national issues","Indian history and geography","Polity and economy","Security and human rights","Analytical comprehension","Precis writing","Counter-terrorism and internal security themes"]}]
},
"ssc-cgl-2026":{slug:"ssc-cgl-2026",title:"SSC CGL — structured syllabus",status:"official-structured",sourceUrl:"https://ssc.gov.in/",lastVerified:"2026-09-27",subjects:[
{subject:"General Intelligence & Reasoning",topics:["Analogies","Classification","Series","Coding-decoding","Venn diagrams","Space visualization","Problem solving","Critical thinking","Pattern folding","Embedded figures","Numerical reasoning"]},
{subject:"General Awareness",topics:["Current events","History","Culture","Geography","Economic scene","General policy","Scientific research","India and neighbouring countries"]},
{subject:"Quantitative Aptitude",topics:["Number system","Percentages","Ratio and proportion","Averages","Interest","Profit and loss","Discount","Partnership","Mixture and allegation","Time and distance","Time and work","Algebra","Geometry","Mensuration","Trigonometry","Data interpretation"]},
{subject:"English Comprehension",topics:["Vocabulary","Grammar","Sentence structure","Synonyms and antonyms","Error spotting","Fill in the blanks","Idioms and phrases","Reading comprehension","Cloze test","Sentence improvement"]},
{subject:"Tier-II Computer Knowledge",topics:["Computer basics","CPU","Input/output devices","Memory","Windows","Microsoft Office","Internet","Email","Networking basics","Cyber security"]},
{subject:"Tier-II Data Entry Speed Test",topics:["Data entry speed","Accuracy","Prescribed computer-based data entry task"]}]
},
"ssc-chsl-2026":{slug:"ssc-chsl-2026",title:"SSC CHSL — structured syllabus",status:"official-structured",sourceUrl:"https://ssc.gov.in/",lastVerified:"2026-09-27",subjects:[
{subject:"English Language",topics:["Spot the error","Fill in the blanks","Synonyms","Antonyms","Spellings","Idioms","One-word substitution","Sentence improvement","Active/passive","Direct/indirect speech","Cloze test","Comprehension"]},
{subject:"General Intelligence",topics:["Analogy","Classification","Series","Coding-decoding","Venn diagrams","Figural classification","Embedded figures","Pattern folding","Logical reasoning"]},
{subject:"Quantitative Aptitude",topics:["Number system","Arithmetic","Algebra","Geometry","Mensuration","Trigonometry","Statistical charts","Data interpretation"]},
{subject:"General Awareness",topics:["Current affairs","History","Culture","Geography","Economic scene","General policy","Scientific research","India and neighbouring countries"]},
{subject:"Computer Knowledge",topics:["Computer fundamentals","Operating systems","Word processing","Spreadsheets","Internet and email","Cyber security"]}]
},
"ssc-mts-2026":{slug:"ssc-mts-2026",title:"SSC MTS — structured syllabus",status:"official-structured",sourceUrl:"https://ssc.gov.in/",lastVerified:"2026-09-27",subjects:[
{subject:"Numerical & Mathematical Ability",topics:["Integers","Whole numbers","LCM and HCF","Decimals and fractions","BODMAS","Percentage","Ratio","Work and time","Average","Simple interest","Profit and loss","Discount","Area and perimeter","Distance and time","Graphs and data"]},
{subject:"Reasoning Ability & Problem Solving",topics:["Alpha-numeric series","Coding-decoding","Analogy","Directions","Similarities and differences","Jumbling","Problem solving","Non-verbal reasoning"]},
{subject:"General Awareness",topics:["History","Geography","Civics","Economics","General science","Environmental studies","Current affairs"]},
{subject:"English Language & Comprehension",topics:["Vocabulary","Grammar","Sentence structure","Synonyms","Antonyms","Reading comprehension"]}]
},
"ssc-je-2026":{slug:"ssc-je-2026",title:"SSC Junior Engineer — structured syllabus",status:"official-structured",sourceUrl:"https://ssc.gov.in/ro-nodal/",lastVerified:"2026-09-27",subjects:[
{subject:"General Intelligence & Reasoning",topics:["Analogy","Classification","Series","Coding-decoding","Venn diagrams","Problem solving","Judgment","Decision making","Visual memory"]},
{subject:"General Awareness",topics:["Current events","History","Culture","Geography","Economic scene","General policy","Scientific research"]},
{subject:"Civil Engineering",topics:["Building materials","Estimating and costing","Surveying","Soil mechanics","Hydraulics","Irrigation","Transportation","Environmental engineering","Theory of structures","Concrete technology","Steel design"]},
{subject:"Electrical Engineering",topics:["Basic concepts","Circuit law","Magnetic effect","AC fundamentals","Measurements","Electrical machines","Generation","Transmission and distribution","Estimation and costing","Utilization","Basic electronics"]},
{subject:"Mechanical Engineering",topics:["Theory of machines","Machine design","Engineering mechanics","Thermodynamics","IC engines","Refrigeration","Production engineering","Properties of materials","Fluid mechanics","Power plant engineering"]}]
},
"ssc-gd-2026":{slug:"ssc-gd-2026",title:"SSC GD Constable — structured syllabus",status:"official-structured",sourceUrl:"https://ssc.gov.in/ro-nodal/",lastVerified:"2026-09-27",subjects:[
{subject:"General Intelligence & Reasoning",topics:["Analogies","Similarities","Differences","Spatial visualization","Spatial orientation","Visual memory","Observation","Relationship concepts","Arithmetic reasoning","Figural classification","Number series","Non-verbal series"]},
{subject:"General Knowledge & General Awareness",topics:["Current events","India and neighbouring countries","Sports","History","Culture","Geography","Economic scene","General polity","Indian Constitution","Scientific research"]},
{subject:"Elementary Mathematics",topics:["Number system","Whole numbers","Decimals","Fractions","Arithmetic","Percentage","Ratio","Average","Interest","Profit and loss","Discount","Mensuration","Time and distance","Ratio and time","Time and work"]},
{subject:"English/Hindi",topics:["Basic comprehension","Vocabulary","Grammar","Sentence understanding","Reading comprehension"]}]
},
"ctet-2026":{slug:"ctet-2026",title:"CTET — structured syllabus",status:"official-structured",sourceUrl:"https://ctet.nic.in/information-bulletin/",lastVerified:"2026-09-27",subjects:[
{subject:"Child Development & Pedagogy",topics:["Child development","Concept of inclusive education","Understanding children with special needs","Learning and pedagogy","How children think and learn","Motivation and learning","Individual differences"]},
{subject:"Language I",topics:["Language comprehension","Pedagogy of language development","Reading","Grammar and language use","Learning and teaching language"]},
{subject:"Language II",topics:["Comprehension","Pedagogy of language development","Communication","Remedial teaching","Language skills"]},
{subject:"Mathematics — Paper I",topics:["Number","Geometry","Shapes and spatial understanding","Measurement","Data handling","Patterns","Mathematics pedagogy"]},
{subject:"Environmental Studies — Paper I",topics:["Family and friends","Food","Shelter","Water","Travel","Things we make and do","EVS pedagogy"]},
{subject:"Mathematics & Science — Paper II",topics:["Number system","Algebra","Geometry","Mensuration","Data handling","Food","Materials","Living world","Moving things","Electricity and circuits","Magnets","Natural phenomena","Natural resources","Science pedagogy"]},
{subject:"Social Studies/Social Science — Paper II",topics:["History","Geography","Social and political life","Constitution","Democracy","Resources","Government","Social science pedagogy"]}]
},
"neet-ug-2026":{slug:"neet-ug-2026",title:"NEET UG 2026 — structured syllabus",status:"official-structured",sourceUrl:"https://neet.nta.nic.in/documents/",lastVerified:"2026-09-27",subjects:[
{subject:"Physics",topics:["Units and measurements","Kinematics","Laws of motion","Work, energy and power","Rotational motion","Gravitation","Properties of bulk matter","Thermodynamics","Kinetic theory","Oscillations and waves","Electrostatics","Current electricity","Magnetic effects","Electromagnetic induction","Alternating current","Electromagnetic waves","Optics","Dual nature","Atoms and nuclei","Electronic devices"]},
{subject:"Chemistry",topics:["Some basic concepts","Atomic structure","Chemical bonding","Thermodynamics","Equilibrium","Redox reactions","Organic chemistry principles","Hydrocarbons","Solutions","Electrochemistry","Chemical kinetics","Surface chemistry","p-block","d- and f-block","Coordination compounds","Haloalkanes and haloarenes","Alcohols phenols ethers","Aldehydes ketones acids","Amines","Biomolecules"]},
{subject:"Biology",topics:["Diversity in living world","Structural organisation","Cell structure and function","Plant physiology","Human physiology","Reproduction","Genetics and evolution","Biology and human welfare","Biotechnology","Ecology and environment"]}]
},
"ugc-net-2026":{slug:"ugc-net-2026",title:"UGC-NET — structured syllabus framework",status:"official-structured",sourceUrl:"https://ugcnet.nta.ac.in/",lastVerified:"2026-09-27",subjects:[
{subject:"Paper I — Teaching & Research Aptitude",topics:["Teaching aptitude","Research aptitude","Comprehension","Communication","Mathematical reasoning","Logical reasoning","Data interpretation","Information and communication technology","People and environment","Higher education system"]},
{subject:"Paper II — Subject specific",topics:["Candidate-selected UGC-NET subject","Official subject-specific syllabus","Unit-wise concepts and theories","Subject-specific research and application areas","Current official subject syllabus must be followed"]}]
},
"jpsc-2026":{slug:"jpsc-2026",title:"JPSC Combined Civil Services — structured syllabus",status:"official-structured",sourceUrl:"https://www.jpsc.gov.in/",lastVerified:"2026-09-27",subjects:[
{subject:"Prelims Paper I — General Studies",topics:["History of India","Geography of India","Indian polity and governance","Indian economy","General science","Environment","Current affairs","Jharkhand history and culture","Jharkhand geography","Jharkhand economy","Jharkhand state administration"]},
{subject:"Prelims Paper II — General Studies",topics:["General aptitude","Reasoning","Numerical ability","Comprehension","Mental ability","General awareness"]},
{subject:"Mains — General Hindi & General English",topics:["Essay","Precis","Comprehension","Grammar","Translation","Vocabulary","Correct usage"]},
{subject:"Mains — General Studies",topics:["History","Geography","Polity","Economy","Science and technology","Environment","Current affairs","Jharkhand-specific studies"]},
{subject:"Mains — Optional / prescribed papers",topics:["Subject-specific papers according to the current JPSC notification and rules"]}]
},
,
"family-upsc-ifs":{slug:"family-upsc-ifs",title:"Indian Forest Service Examination (IFoS) — official syllabus source",status:"official-source",sourceUrl:"https://upsc.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-upsc-ese":{slug:"family-upsc-ese",title:"Engineering Services Examination (ESE/IES) — official syllabus source",status:"official-source",sourceUrl:"https://upsc.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-upsc-cms":{slug:"family-upsc-cms",title:"Combined Medical Services Examination (CMS) — official syllabus source",status:"official-source",sourceUrl:"https://upsc.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-upsc-ies-iss":{slug:"family-upsc-ies-iss",title:"Indian Economic Service / Indian Statistical Service — official syllabus source",status:"official-source",sourceUrl:"https://upsc.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-upsc-geoscientist":{slug:"family-upsc-geoscientist",title:"Combined Geo-Scientist Examination — official syllabus source",status:"official-source",sourceUrl:"https://upsc.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-upsc-epfo":{slug:"family-upsc-epfo",title:"EPFO recruitment examinations — official syllabus source",status:"official-source",sourceUrl:"https://upsc.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-upsc-ora":{slug:"family-upsc-ora",title:"UPSC Recruitment / ORA Posts — official syllabus source",status:"official-source",sourceUrl:"https://upsc.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-ssc-cpo":{slug:"family-ssc-cpo",title:"SSC Sub-Inspector in Delhi Police & CAPFs — official syllabus source",status:"official-source",sourceUrl:"https://ssc.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-ssc-je":{slug:"family-ssc-je",title:"SSC Junior Engineer — official syllabus source",status:"official-source",sourceUrl:"https://ssc.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-ssc-stenographer":{slug:"family-ssc-stenographer",title:"SSC Stenographer Grade C & D — official syllabus source",status:"official-source",sourceUrl:"https://ssc.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-ssc-jht":{slug:"family-ssc-jht",title:"SSC Junior Hindi Translator — official syllabus source",status:"official-source",sourceUrl:"https://ssc.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-ssc-selection-post":{slug:"family-ssc-selection-post",title:"SSC Selection Post — official syllabus source",status:"official-source",sourceUrl:"https://ssc.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-ssc-gd":{slug:"family-ssc-gd",title:"SSC GD Constable — official syllabus source",status:"official-source",sourceUrl:"https://ssc.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-rrb-alp":{slug:"family-rrb-alp",title:"RRB Assistant Loco Pilot — official syllabus source",status:"official-source",sourceUrl:"https://indianrailways.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-rrb-technician":{slug:"family-rrb-technician",title:"RRB Technician — official syllabus source",status:"official-source",sourceUrl:"https://indianrailways.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-rrb-je":{slug:"family-rrb-je",title:"RRB Junior Engineer — official syllabus source",status:"official-source",sourceUrl:"https://indianrailways.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-rrb-paramedical":{slug:"family-rrb-paramedical",title:"RRB Paramedical Categories — official syllabus source",status:"official-source",sourceUrl:"https://indianrailways.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-rrb-ntpc-ug":{slug:"family-rrb-ntpc-ug",title:"RRB NTPC Undergraduate — official syllabus source",status:"official-source",sourceUrl:"https://indianrailways.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-rrb-rpf-si":{slug:"family-rrb-rpf-si",title:"RPF Sub-Inspector — official syllabus source",status:"official-source",sourceUrl:"https://rpf.indianrailways.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-rrb-rpf-constable":{slug:"family-rrb-rpf-constable",title:"RPF Constable — official syllabus source",status:"official-source",sourceUrl:"https://rpf.indianrailways.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-ibps-rrb-office-assistant":{slug:"family-ibps-rrb-office-assistant",title:"IBPS RRB Office Assistant — official syllabus source",status:"official-source",sourceUrl:"https://ibps.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-ibps-rrb-officer":{slug:"family-ibps-rrb-officer",title:"IBPS RRB Officer Scale I/II/III — official syllabus source",status:"official-source",sourceUrl:"https://ibps.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-ibps-so":{slug:"family-ibps-so",title:"IBPS Specialist Officer — official syllabus source",status:"official-source",sourceUrl:"https://ibps.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-sbi-clerk":{slug:"family-sbi-clerk",title:"SBI Junior Associate — official syllabus source",status:"official-source",sourceUrl:"https://sbi.co.in/web/careers",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-sbi-so":{slug:"family-sbi-so",title:"SBI Specialist Cadre Officer — official syllabus source",status:"official-source",sourceUrl:"https://sbi.co.in/web/careers",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-rbi-grade-b":{slug:"family-rbi-grade-b",title:"RBI Grade B — official syllabus source",status:"official-source",sourceUrl:"https://rbi.org.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-rbi-assistant":{slug:"family-rbi-assistant",title:"RBI Assistant — official syllabus source",status:"official-source",sourceUrl:"https://rbi.org.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-nabard-grade-a":{slug:"family-nabard-grade-a",title:"NABARD Grade A — official syllabus source",status:"official-source",sourceUrl:"https://nabard.org",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-sebi-grade-a":{slug:"family-sebi-grade-a",title:"SEBI Grade A — official syllabus source",status:"official-source",sourceUrl:"https://sebi.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-lic-aao":{slug:"family-lic-aao",title:"LIC Assistant Administrative Officer — official syllabus source",status:"official-source",sourceUrl:"https://licindia.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-niacl-ao":{slug:"family-niacl-ao",title:"NIACL Administrative Officer — official syllabus source",status:"official-source",sourceUrl:"https://newindia.co.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-afcat":{slug:"family-afcat",title:"AFCAT — official syllabus source",status:"official-source",sourceUrl:"https://afcat.cdac.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-agniveer-airforce":{slug:"family-agniveer-airforce",title:"Agniveervayu — official syllabus source",status:"official-source",sourceUrl:"https://agnipathvayu.cdac.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-agniveer-army":{slug:"family-agniveer-army",title:"Agniveer Recruitment — official syllabus source",status:"official-source",sourceUrl:"https://joinindianarmy.nic.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-agniveer-navy":{slug:"family-agniveer-navy",title:"Agniveer Navy — official syllabus source",status:"official-source",sourceUrl:"https://joinindiannavy.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-coast-guard":{slug:"family-coast-guard",title:"Indian Coast Guard Recruitment — official syllabus source",status:"official-source",sourceUrl:"https://joinindiancoastguard.cdac.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-csir-net":{slug:"family-csir-net",title:"CSIR UGC NET — official syllabus source",status:"official-source",sourceUrl:"https://csirnet.nta.ac.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-neet-mds":{slug:"family-neet-mds",title:"NEET MDS — official syllabus source",status:"official-source",sourceUrl:"https://natboard.edu.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-inicet":{slug:"family-inicet",title:"INI-CET — official syllabus source",status:"official-source",sourceUrl:"https://aiimsexams.ac.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-gate":{slug:"family-gate",title:"GATE — official syllabus source",status:"official-source",sourceUrl:"https://gate2027.iitr.ac.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-jpsc-forest":{slug:"family-jpsc-forest",title:"JPSC Forest / allied recruitment — official syllabus source",status:"official-source",sourceUrl:"https://jpsc.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-jssc-cgl":{slug:"family-jssc-cgl",title:"JSSC Combined Graduate Level — official syllabus source",status:"official-source",sourceUrl:"https://jssc.jharkhand.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-jssc-inter":{slug:"family-jssc-inter",title:"JSSC Intermediate Level — official syllabus source",status:"official-source",sourceUrl:"https://jssc.jharkhand.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-jssc-matric":{slug:"family-jssc-matric",title:"JSSC Matric Level — official syllabus source",status:"official-source",sourceUrl:"https://jssc.jharkhand.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-bssc-cgl":{slug:"family-bssc-cgl",title:"BSSC Combined Graduate Level — official syllabus source",status:"official-source",sourceUrl:"https://bssc.bihar.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-bpsc":{slug:"family-bpsc",title:"BPSC Combined Competitive Examination — official syllabus source",status:"official-source",sourceUrl:"https://bpsc.bih.nic.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-uppsc":{slug:"family-uppsc",title:"UPPSC Combined State / Upper Subordinate Services — official syllabus source",status:"official-source",sourceUrl:"https://uppsc.up.nic.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-mppsc":{slug:"family-mppsc",title:"MPPSC State Service Examination — official syllabus source",status:"official-source",sourceUrl:"https://mppsc.mp.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-rpsc-ras":{slug:"family-rpsc-ras",title:"RPSC Rajasthan Administrative Service — official syllabus source",status:"official-source",sourceUrl:"https://rpsc.rajasthan.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-hpsc-hcs":{slug:"family-hpsc-hcs",title:"HPSC Haryana Civil Services — official syllabus source",status:"official-source",sourceUrl:"https://hpsc.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-mpsc":{slug:"family-mpsc",title:"MPSC State Services — official syllabus source",status:"official-source",sourceUrl:"https://mpsc.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-gpsc":{slug:"family-gpsc",title:"GPSC Class I/II Services — official syllabus source",status:"official-source",sourceUrl:"https://gpsc.gujarat.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-appsc":{slug:"family-appsc",title:"APPSC Group I/II — official syllabus source",status:"official-source",sourceUrl:"https://psc.ap.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-tspsc":{slug:"family-tspsc",title:"TGPSC Group examinations — official syllabus source",status:"official-source",sourceUrl:"https://tspsc.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-kpsc":{slug:"family-kpsc",title:"KPSC Group A/B & other recruitment — official syllabus source",status:"official-source",sourceUrl:"https://kpsc.kar.nic.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-tnpsc-group1":{slug:"family-tnpsc-group1",title:"TNPSC Group I — official syllabus source",status:"official-source",sourceUrl:"https://tnpsc.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-tnpsc-group2":{slug:"family-tnpsc-group2",title:"TNPSC Group II/IIA — official syllabus source",status:"official-source",sourceUrl:"https://tnpsc.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-wbcs":{slug:"family-wbcs",title:"WBPSC WBCS — official syllabus source",status:"official-source",sourceUrl:"https://psc.wb.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-odisha-ocs":{slug:"family-odisha-ocs",title:"OPSC Odisha Civil Services — official syllabus source",status:"official-source",sourceUrl:"https://opsc.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-kerala-psc":{slug:"family-kerala-psc",title:"Kerala PSC — official syllabus source",status:"official-source",sourceUrl:"https://keralapsc.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-india-post-gds":{slug:"family-india-post-gds",title:"India Post Gramin Dak Sevak — official syllabus source",status:"official-source",sourceUrl:"https://indiapostgdsonline.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-india-post-pa-sa":{slug:"family-india-post-pa-sa",title:"India Post Postal Assistant / Sorting Assistant — official syllabus source",status:"official-source",sourceUrl:"https://indiapost.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-fci":{slug:"family-fci",title:"Food Corporation of India Recruitment — official syllabus source",status:"official-source",sourceUrl:"https://fci.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-esic":{slug:"family-esic",title:"ESIC Recruitment — official syllabus source",status:"official-source",sourceUrl:"https://esic.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-epfo":{slug:"family-epfo",title:"EPFO Recruitment — official syllabus source",status:"official-source",sourceUrl:"https://epfindia.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-aiims":{slug:"family-aiims",title:"AIIMS Recruitment — official syllabus source",status:"official-source",sourceUrl:"https://aiimsexams.ac.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-dsssb":{slug:"family-dsssb",title:"DSSSB Recruitment — official syllabus source",status:"official-source",sourceUrl:"https://dsssb.delhi.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-delhi-police":{slug:"family-delhi-police",title:"Delhi Police Recruitment — official syllabus source",status:"official-source",sourceUrl:"https://delhipolice.gov.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
"family-psu-recruitment":{slug:"family-psu-recruitment",title:"PSU Recruitment through GATE / Direct — official syllabus source",status:"official-source",sourceUrl:"https://gate2027.iitr.ac.in",lastVerified:"2026-09-27",subjects:[{subject:"Official syllabus / scheme",topics:["The latest notification and syllabus document published by the authority is the controlling source.","Open the official source below for the current post-wise or subject-wise syllabus.","Syllabus can vary by post, paper, branch, state, recruitment cycle or notification.","SarkariPrep does not invent topic lists where the authority source is not sufficiently structured."]}]},
};