import type { Metadata } from "next";

export const metadata: Metadata = { title: "Government Exams in India | SarkariPrep", description: "Browse Indian government exams across UPSC, SSC, banking, railway, defence, teaching, medical and state recruitment.", alternates: { canonical: "https://sarkariprep.online/exams" }, robots: { index: true, follow: true } };

"use client";
import {useMemo,useState} from "react";
import {exams} from "@/lib/exams";
import {autoExamData} from "@/lib/auto-exam-data";
import {getApplicationState,getExamState,applicationLabel,examLabel} from "@/lib/exam-status";
export default function ExamsDirectory(){
 const[q,setQ]=useState(""); const[cat,setCat]=useState("All"); const[status,setStatus]=useState("All");
 const cats=["All",...Array.from(new Set(exams.map(e=>e.category)))];
 const list=useMemo(()=>exams.filter(e=>{const o=autoExamData[e.slug];const app=getApplicationState(e,o);const exam=getExamState(e,o);const statusOk=status==="All"||(status==="Open"&&app==="open")||(status==="Starting Soon"&&app==="upcoming")||(status==="Upcoming Exam"&&(exam==="upcoming"||exam==="ongoing"))||(status==="Closed"&&app==="closed");return (cat==="All"||e.category===cat)&&statusOk&&(!q||[e.name,e.organization,e.category,e.qualifications].join(" ").toLowerCase().includes(q.toLowerCase()))}),[q,cat,status]);
 return <main><section className="section light"><div className="wrap"><a className="backLink" href="/">← SarkariPrep home</a><div className="sectionHead"><div><span className="eyebrow">EXAM DIRECTORY</span><h1>All Government Exams</h1></div><p>{list.length} exam profiles</p></div><div className="heroSearch directorySearch"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search exam, organisation or qualification…"/></div><div className="filterBar"><div className="filterScroll">{["All","Open Now","Starting Soon","Upcoming Exam","Closed"].map(s=><button className={status===s?"filter active":"filter"} key={s} onClick={()=>setStatus(s)}>{s}</button>)}</div></div><div className="filterBar"><div className="filterScroll">{cats.map(c=><button className={cat===c?"filter active":"filter"} key={c} onClick={()=>setCat(c)}>{c}</button>)}</div></div><div className="examGrid">{list.map(e=>{const o=autoExamData[e.slug];const app=getApplicationState(e,o);const exam=getExamState(e,o);return <article className="examCard" key={e.slug}><div className="examMeta"><span className="tag">{e.category}</span><span className={"statusPill "+(app==="open"?"open":app==="closed"?"closed":app==="upcoming"?"upcoming":"unknown")}>{applicationLabel(app)}</span></div><h3>{e.name}</h3><p className="org">{e.organization}</p><div className="miniFacts"><div><small>Exam status</small><b>{examLabel(exam)}</b></div><div><small>Qualification</small><b>{e.qualifications}</b></div><div><small>Age</small><b>{e.minAge===0?"Check notification":e.minAge+"–"+e.maxAge+" yrs"}</b></div><div><small>Vacancies</small><b>{e.dataStatus==="official-verified"?e.vacancies:"See latest notification"}</b></div></div><p className="cardHint"><b>{applicationLabel(app)}</b> · {examLabel(exam)}. Final dates and eligibility: latest official notification.</p><div className="cardLinks"><a className="primaryLink" href={"/exams/"+e.slug}>Easy guide →</a><a href={e.notificationUrl||e.sourceUrl||e.officialUrl} target="_blank" rel="noopener noreferrer">Latest notification ↗</a></div></article>})}</div></div></section><section className="section compact"><div className="wrap"><div className="detailCard contactCard"><span className="eyebrow">EXAM HELP & NOTES</span><h2>Notes ya kisi particular exam/job ke baare mein poochna hai?</h2><p>WhatsApp ya Gmail par directly enquiry bhej sakte hain.</p><div className="cardLinks"><a className="primaryLink" href="https://wa.me/917979748481?text=Hello%20SarkariPrep%2C%20mujhe%20exam%20notes%20ya%20exam%20information%20chahiye." target="_blank" rel="noopener noreferrer">WhatsApp · 7979748481 ↗</a><a href="mailto:saheebmahmood5@gmail.com?subject=SarkariPrep%20Exam%20%2F%20Notes%20Enquiry">Gmail · saheebmahmood5@gmail.com</a></div></div></div></section></main>
}