import {NextResponse} from "next/server";
import {del,get,list} from "@vercel/blob";
import webpush from "web-push";
import {autoNotifications} from "@/lib/auto-notifications";
import {discoveredOfficialNotices} from "@/lib/discovered-official-notices";
import {cleanFeedTitle,isFeedUseful} from "@/lib/notification-feed";
export const runtime="nodejs";export const dynamic="force-dynamic";
function auth(req:Request){const expected=process.env.CRON_SECRET;return !!expected&&req.headers.get("authorization")==="Bearer "+expected}
async function allBlobs(){let cursor:string|undefined;const all:any[]=[];do{const r=await list({prefix:"subscriptions/",access:"private",cursor});all.push(...r.blobs);cursor=r.cursor||undefined}while(cursor);return all}
async function readBlob(url:string){const r=await get(url,{access:"private"});if(!r||r.statusCode!==200)return null;return JSON.parse(await new Response(r.stream).text())}
export async function GET(req:Request){if(!auth(req))return NextResponse.json({error:"Unauthorized"},{status:401});if(!process.env.VAPID_PUBLIC_KEY||!process.env.VAPID_PRIVATE_KEY||!process.env.VAPID_SUBJECT)return NextResponse.json({error:"VAPID is not configured"},{status:503});webpush.setVapidDetails(process.env.VAPID_SUBJECT,process.env.VAPID_PUBLIC_KEY,process.env.VAPID_PRIVATE_KEY);const feed=[...autoNotifications,...discoveredOfficialNotices].filter(n=>isFeedUseful(n)).sort((a,b)=>new Date(b.publishedDate||b.lastChecked).getTime()-new Date(a.publishedDate||a.lastChecked).getTime());const top=feed.slice(0,3);if(!top.length)return NextResponse.json({ok:true,skipped:true,reason:"no-useful-updates"});const payload=JSON.stringify({title:"🇮🇳 SarkariPrep — New Government Updates",body:top.map(n=>cleanFeedTitle(n.title)).join(" • ").slice(0,220),url:"/notifications",tag:"daily-government-update"});const blobs=await allBlobs();let sent=0,removed=0;for(const blob of blobs){try{const record=await readBlob(blob.url);if(!record?.subscription)continue;await webpush.sendNotification(record.subscription,payload);sent++}catch(error:any){if(error?.statusCode===404||error?.statusCode===410){await del(blob.url);removed++}}}return NextResponse.json({ok:true,sent,removed,headlineCount:top.length})}
