import {NextResponse} from "next/server";
import webpush from "web-push";
import {Redis} from "@upstash/redis";
import {autoNotifications} from "@/lib/auto-notifications";
import {discoveredOfficialNotices} from "@/lib/discovered-official-notices";
import {cleanFeedTitle,isFeedUseful} from "@/lib/notification-feed";
export const runtime="nodejs";export const dynamic="force-dynamic";
function redis(){if(!process.env.KV_REST_API_URL||!process.env.KV_REST_API_TOKEN)return null;return new Redis({url:process.env.KV_REST_API_URL,token:process.env.KV_REST_API_TOKEN})}
function auth(req:Request){const expected=process.env.CRON_SECRET;return !!expected&&req.headers.get("authorization")==="Bearer "+expected}
export async function GET(req:Request){if(!auth(req))return NextResponse.json({error:"Unauthorized"},{status:401});if(!process.env.VAPID_PUBLIC_KEY||!process.env.VAPID_PRIVATE_KEY||!process.env.VAPID_SUBJECT)return NextResponse.json({error:"VAPID is not configured"},{status:503});const store=redis();if(!store)return NextResponse.json({error:"Push storage is not configured"},{status:503});webpush.setVapidDetails(process.env.VAPID_SUBJECT,process.env.VAPID_PUBLIC_KEY,process.env.VAPID_PRIVATE_KEY);const today=new Date().toISOString().slice(0,10);const last=await store.get<string>("sarkariprep:push:last-daily");if(last===today)return NextResponse.json({ok:true,skipped:true,reason:"already-sent"});const feed=[...autoNotifications,...discoveredOfficialNotices].filter(n=>isFeedUseful(n)).sort((a,b)=>new Date(b.publishedDate||b.lastChecked).getTime()-new Date(a.publishedDate||a.lastChecked).getTime());const top=feed.slice(0,3);if(!top.length)return NextResponse.json({ok:true,skipped:true,reason:"no-useful-updates"});const payload=JSON.stringify({title:"🇮🇳 SarkariPrep — New Government Updates",body:top.map(n=>cleanFeedTitle(n.title)).join(" • ").slice(0,220),url:"/notifications",tag:"daily-government-update"});const entries=await store.hgetall<Record<string,string>>("sarkariprep:push:subscriptions");let sent=0,removed=0;for(const [endpoint,raw] of Object.entries(entries||{})){try{await webpush.sendNotification(JSON.parse(raw).subscription,payload);sent++}catch(error:any){if(error?.statusCode===404||error?.statusCode===410){await store.hdel("sarkariprep:push:subscriptions",endpoint);removed++}}}await store.set("sarkariprep:push:last-daily",today);return NextResponse.json({ok:true,sent,removed,headlineCount:top.length})}
